# core/localization.py

"""
Uygulama genelindeki tüm metin anahtarlarının dil çevirilerini içerir.
Yeni bir dil eklemek için, 'TRANSLATIONS' sözlüğüne yeni bir anahtar 
(örn: 'de' Almanca için) ve ilgili çeviri sözlüklerini ekleyin.
"""
import json

LANGUAGE_NAMES = {
    'ar': 'Arabic',
    'bg': 'Bulgarian',
    'de': 'German',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'th': 'Thai',
    'tr': 'Turkish',
    'zh': 'Chinese'
}

TRANSLATIONS = {
    "en": {
        "colors": {
            "white": "White", "gray": "Gray", "fume": "Charcoal", "black": "Black", "cream": "Cream", "beige": "Beige",
            "tan": "Tan", "cinnamon": "Cinnamon", "earth": "Earth", "chestnut": "Chestnut", "plum": "Plum",
            "khaki": "Khaki", "lemon": "Lemon", "yellow": "Yellow", "gold": "Gold", "mustard": "Mustard",
            "peach": "Peach", "apricot": "Apricot", "salmon": "Salmon", "orange": "Orange", "dusty-pink": "Dusty Rose",
            "coral": "Coral", "pomegranate-red": "Pomegranate", "red": "Red", "cherry-red": "Cherry", "dark-red": "Burgundy",
            "pink": "Pink", "fuchsia": "Fuchsia", "lilac": "Lilac", "lavender": "Lavender", "violet": "Violet",
            "purple": "Purple", "ice-blue": "Ice Blue", "turquoise": "Turquoise", "blue": "Blue",
            "saxony-blue": "Royal Blue", "navy": "Navy", "mint": "Mint", "water-green": "Aqua Green",
            "grass-green": "Grass Green", "emerald": "Emerald", "green": "Green", "olive": "Olive", "silver": "Silver",
            "bronze": "Bronze", "leopard": "Leopard", "zebra": "Zebra", "snakeskin": "Snakeskin", "striped": "Striped",
            "plaid": "Plaid", "floral": "Floral", "polka-dot": "Polka Dot"
        },
        "categories": {
            "top": "Top Wear", "bottom": "Bottom Wear", "dresses-jumpsuits": "Dresses & Jumpsuits",
            "outerwear": "Outerwear", "shoes": "Shoes", "bags": "Bags", "accessories": "Accessories", "suits": "Suits",
            "t-shirt": "T-Shirt", "blouse": "Blouse", "shirt": "Shirt", "sweater": "Sweater", "pullover": "Pullover",
            "sweatshirt": "Sweatshirt", "hoodie": "Hoodie", "track-top": "Track Top", "crop-top": "Crop Top",
            "tank-top": "Tank Top", "bodysuit": "Bodysuit", "vest": "Vest", "tunic": "Tunic", "bralette": "Bralette",
            "jeans": "Jeans", "trousers": "Trousers", "linen-trousers": "Linen Trousers", "leggings": "Leggings",
            "track-bottom": "Track Bottom", "mini-skirt": "Mini Skirt", "midi-skirt": "Midi Skirt", "long-skirt": "Long Skirt",
            "denim-shorts": "Denim Shorts", "fabric-shorts": "Fabric Shorts", "athletic-shorts": "Athletic Shorts",
            "bermuda-shorts": "Bermuda Shorts", "capri-pants": "Capri Pants", "casual-dress": "Casual Dress",
            "evening-dress": "Evening Dress", "sporty-dress": "Sporty Dress", "modest-dress": "Modest Dress",
            "modest-evening-dress": "Modest Evening Dress", "jumpsuit": "Jumpsuit", "romper": "Romper",
            "puffer-coat": "Puffer Coat", "raincoat": "Raincoat", "denim-jacket": "Denim Jacket",
            "leather-jacket": "Leather Jacket", "fabric-jacket": "Fabric Jacket", "bomber-jacket": "Bomber Jacket",
            "overcoat": "Overcoat", "coat": "Coat", "trenchcoat": "Trenchcoat", "blazer": "Blazer",
            "cardigan": "Cardigan", "abaya": "Abaya", "sneakers": "Sneakers", "casual-sport-shoes": "Casual Sport Shoes",
            "heels": "Heels", "boots": "Boots", "tall-boots": "Tall Boots", "flats": "Flats", "loafers": "Loafers",
            "bootie": "Bootie", "sandals": "Sandals", "slippers": "Slippers", "classic-shoes": "Classic Shoes",
            "handbag": "Handbag", "backpack": "Backpack", "shoulder-bag": "Shoulder Bag", "briefcase": "Briefcase",
            "crossbody-bag": "Crossbody Bag", "necklace": "Necklace", "earrings": "Earrings", "ring": "Ring",
            "bracelet": "Bracelet", "scarf": "Scarf", "hijab": "Hijab", "shawl": "Shawl", "sunglasses": "Sunglasses",
            "belt": "Belt", "hat": "Hat", "watch": "Watch", "tie": "Tie", "suit-jacket": "Suit Jacket",
            "suit-trousers": "Suit Trousers", "tuxedo": "Tuxedo", "polo-shirt": "Polo Shirt"
        },
        "occasions": {
            "categories": { "casual": "Casual", "work": "Work & Professional", "formal": "Celebration & Formal", "social": "Social", "active": "Active & Sports", "special": "Travel & Special" },
            "daily-errands": "Daily Errands", "friends-gathering": "Friends Gathering", "weekend-brunch": "Weekend Brunch", "coffee-date": "Coffee", "shopping": "Shopping", "walk": "A Walk", "office-day": "Day at the Office", "business-meeting": "Business Meeting", "business-lunch": "Business Lunch", "networking": "Networking Event", "university": "University / Class", "wedding": "Wedding", "special-event": "Special Event", "celebration": "Celebration", "formal-dinner": "Formal Dinner", "dinner-date": "Dinner Date", "birthday-party": "Birthday Party", "concert": "Concert", "night-out": "Night Out", "house-party": "House Party", "gym": "Gym / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Outdoor Sports", "hiking": "Hiking", "travel": "Travel", "weekend-getaway": "Weekend Getaway", "holiday": "Holiday", "festival": "Festival", "sightseeing": "Sightseeing"
        }
    },
    "tr": {
        "colors": {
            "white": "Beyaz", "gray": "Gri", "fume": "Füme", "black": "Siyah", "cream": "Krem", "beige": "Bej",
            "tan": "Taba", "cinnamon": "Tarçın", "earth": "Toprak", "chestnut": "Kestane", "plum": "Mürdüm",
            "khaki": "Haki", "lemon": "Limon", "yellow": "Sarı", "gold": "Altın", "mustard": "Hardal",
            "peach": "Şeftali", "apricot": "Yavruağzı", "salmon": "Somon", "orange": "Portakal",
            "dusty-pink": "Toz Pembe", "coral": "Mercan", "pomegranate-red": "Nar Çiçeği", "red": "Kırmızı",
            "cherry-red": "Kiraz", "dark-red": "Vişne", "pink": "Pembe", "fuchsia": "Fuşya", "lilac": "Leylak",
            "lavender": "Lavanta", "violet": "Menekşe", "purple": "Mor", "ice-blue": "Buz Mavisi", "turquoise": "Turkuaz",
            "blue": "Mavi", "saxony-blue": "Saks Mavisi", "navy": "Lacivert", "mint": "Nane", "water-green": "Su Yeşili",
            "grass-green": "Çimen Yeşili", "emerald": "Zümrüt", "green": "Yeşil", "olive": "Zeytin Yeşili",
            "silver": "Gümüş", "bronze": "Bronz", "leopard": "Leopar", "zebra": "Zebra", "snakeskin": "Yılan",
            "striped": "Çizgili", "plaid": "Kareli", "floral": "Çiçekli", "polka-dot": "Puantiye"
        },
        "categories": {
            "top": "Üst Giyim", "bottom": "Alt Giyim", "dresses-jumpsuits": "Elbise & Tulum",
            "outerwear": "Dış Giyim", "shoes": "Ayakkabı", "bags": "Çanta", "accessories": "Aksesuar", "suits": "Takım Elbise",
            "t-shirt": "Tişört", "blouse": "Bluz", "shirt": "Gömlek", "sweater": "Kazak", "pullover": "Süveter",
            "sweatshirt": "Sweatshirt", "hoodie": "Kapüşonlu Sweatshirt", "track-top": "Eşofman Üstü",
            "crop-top": "Crop Top", "tank-top": "Atlet", "bodysuit": "Bodysuit", "vest": "Yelek",
            "tunic": "Tunik", "bralette": "Bralet", "jeans": "Kot Pantolon", "trousers": "Kumaş Pantolon",
            "linen-trousers": "Keten Pantolon", "leggings": "Tayt", "track-bottom": "Eşofman Altı",
            "mini-skirt": "Mini Etek", "midi-skirt": "Midi Etek", "long-skirt": "Uzun Etek",
            "denim-shorts": "Kot Şort", "fabric-shorts": "Kumaş Şort", "athletic-shorts": "Spor Şort",
            "bermuda-shorts": "Bermuda Şort", "capri-pants": "Kapri", "casual-dress": "Günlük Elbise",
            "evening-dress": "Gece Elbisesi", "sporty-dress": "Spor Elbise", "modest-dress": "Tesettür Elbise",
            "modest-evening-dress": "Tesettür Abiye", "jumpsuit": "Tulum", "romper": "Şort Tulum",
            "puffer-coat": "Şişme Mont", "raincoat": "Yağmurluk", "denim-jacket": "Kot Ceket",
            "leather-jacket": "Deri Ceket", "fabric-jacket": "Kumaş Ceket", "bomber-jacket": "Bomber Ceket",
            "overcoat": "Palto", "coat": "Kaban", "trenchcoat": "Trençkot", "blazer": "Blazer",
            "cardigan": "Hırka", "abaya": "Ferace", "sneakers": "Sneakers", "casual-sport-shoes": "Casual Spor",
            "heels": "Topuklu Ayakkabı", "boots": "Bot", "tall-boots": "Çizme", "flats": "Babet",
            "loafers": "Loafer", "bootie": "Bot", "sandals": "Sandalet", "slippers": "Terlik",
            "classic-shoes": "Klasik Ayakkabı", "handbag": "El Çantası", "backpack": "Sırt Çantası",
            "shoulder-bag": "Omuz Çantası", "briefcase": "Evrak Çantası", "crossbody-bag": "Çapraz Çanta",
            "necklace": "Kolye", "earrings": "Küpe", "ring": "Yüzük", "bracelet": "Bileklik",
            "scarf": "Eşarp", "hijab": "Başörtüsü", "shawl": "Şal", "sunglasses": "Güneş Gözlüğü",
            "belt": "Kemer", "hat": "Şapka", "watch": "Saat", "tie": "Kravat", "suit-jacket": "Takım Ceket",
            "suit-trousers": "Takım Pantolon", "tuxedo": "Smokin", "polo-shirt": "Polo Tişört"
        },
        "occasions": {
            "categories": { "casual": "Günlük", "work": "İş & Profesyonel", "formal": "Kutlama & Resmi", "social": "Sosyal", "active": "Aktif & Spor", "special": "Seyahat & Özel" },
            "daily-errands": "Günlük İşler", "friends-gathering": "Arkadaş Buluşması", "weekend-brunch": "Hafta Sonu Kahvaltısı", "coffee-date": "Kahve", "shopping": "Alışveriş", "walk": "Yürüyüş", "office-day": "Ofis Günü", "business-meeting": "İş Toplantısı", "business-lunch": "İş Yemeği", "networking": "Sektörel Buluşma", "university": "Üniversite / Ders", "wedding": "Düğün", "special-event": "Özel Etkinlik", "celebration": "Kutlama", "formal-dinner": "Resmi Akşam Yemeği", "dinner-date": "Akşam Yemeği Randevusu", "birthday-party": "Doğum Günü Partisi", "concert": "Konser", "night-out": "Gece Dışarı Çıkma", "house-party": "Ev Partisi", "gym": "Spor Salonu / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Açık Hava Sporları", "hiking": "Doğa Yürüyüşü", "travel": "Seyahat", "weekend-getaway": "Hafta Sonu Kaçamağı", "holiday": "Tatil", "festival": "Festival", "sightseeing": "Gezi"
        }
    },
    "de": {
        "colors": {
            "white": "Weiß", "gray": "Grau", "fume": "Anthrazit", "black": "Schwarz", "cream": "Creme", "beige": "Beige", "tan": "Hellbraun", "cinnamon": "Zimt", "earth": "Erdfarben", "chestnut": "Kastanie", "plum": "Pflaume", "khaki": "Khaki", "lemon": "Zitrone", "yellow": "Gelb", "gold": "Gold", "mustard": "Senf", "peach": "Pfirsich", "apricot": "Aprikose", "salmon": "Lachs", "orange": "Orange", "dusty-pink": "Altrosa", "coral": "Koralle", "pomegranate-red": "Granatapfel", "red": "Rot", "cherry-red": "Kirsche", "dark-red": "Burgund", "pink": "Pink", "fuchsia": "Fuchsia", "lilac": "Flieder", "lavender": "Lavendel", "violet": "Violett", "purple": "Lila", "ice-blue": "Eisblau", "turquoise": "Türkis", "blue": "Blau", "saxony-blue": "Königsblau", "navy": "Marineblau", "mint": "Minze", "water-green": "Aquagrün", "grass-green": "Grasgrün", "emerald": "Smaragd", "green": "Grün", "olive": "Olive", "silver": "Silber", "bronze": "Bronze", "leopard": "Leopard", "zebra": "Zebra", "snakeskin": "Schlangenhaut", "striped": "Gestreift", "plaid": "Schottenmuster", "floral": "Geblümt", "polka-dot": "Gepunktet"
        },
        "categories": {
            "top": "Oberteile", "t-shirt": "T-Shirt", "blouse": "Bluse", "shirt": "Hemd", "sweater": "Pullover", "pullover": "Pullover", "sweatshirt": "Sweatshirt", "hoodie": "Kapuzenpullover", "track-top": "Trainingsjacke", "crop-top": "Crop-Top", "tank-top": "Tank-Top", "bodysuit": "Body", "vest": "Weste", "tunic": "Tunika", "bralette": "Bralette", "bottom": "Unterteile", "jeans": "Jeans", "trousers": "Hosen", "linen-trousers": "Leinenhosen", "leggings": "Leggings", "track-bottom": "Trainingshose", "mini-skirt": "Minirock", "midi-skirt": "Midirock", "long-skirt": "Langer Rock", "denim-shorts": "Jeans-Shorts", "fabric-shorts": "Stoff-Shorts", "athletic-shorts": "Sport-Shorts", "bermuda-shorts": "Bermuda-Shorts", "capri-pants": "Caprihose", "dresses-jumpsuits": "Kleider & Jumpsuits", "casual-dress": "Freizeitkleid", "evening-dress": "Abendkleid", "sporty-dress": "Sportliches Kleid", "modest-dress": "Dezentes Kleid", "modest-evening-dress": "Dezentes Abendkleid", "jumpsuit": "Jumpsuit", "romper": "Romper", "outerwear": "Oberbekleidung", "puffer-coat": "Daunenmantel", "raincoat": "Regenmantel", "denim-jacket": "Jeansjacke", "leather-jacket": "Lederjacke", "fabric-jacket": "Stoffjacke", "bomber-jacket": "Bomberjacke", "overcoat": "Mantel", "coat": "Mantel", "trenchcoat": "Trenchcoat", "blazer": "Blazer", "cardigan": "Strickjacke", "abaya": "Abaya", "shoes": "Schuhe", "sneakers": "Sneaker", "casual-sport-shoes": "Freizeit-Sportschuhe", "heels": "Absatzschuhe", "boots": "Stiefel", "tall-boots": "Hohe Stiefel", "flats": "Flache Schuhe", "loafers": "Loafer", "bootie": "Stiefelette", "sandals": "Sandalen", "slippers": "Hausschuhe", "classic-shoes": "Klassische Schuhe", "bags": "Taschen", "handbag": "Handtasche", "backpack": "Rucksack", "shoulder-bag": "Schultertasche", "briefcase": "Aktentasche", "crossbody-bag": "Umhängetasche", "accessories": "Accessoires", "necklace": "Halskette", "earrings": "Ohrringe", "ring": "Ring", "bracelet": "Armband", "scarf": "Schal", "hijab": "Hidschab", "shawl": "Tuch", "sunglasses": "Sonnenbrille", "belt": "Gürtel", "hat": "Hut", "watch": "Uhr", "tie": "Krawatte", "suits": "Anzüge", "suit-jacket": "Sakko", "suit-trousers": "Anzughose", "tuxedo": "Smoking", "polo-shirt": "Polo-Shirt"
        },
        "occasions": {
            "categories": { "casual": "Freizeit", "work": "Arbeit & Beruf", "formal": "Feier & Formell", "social": "Soziales", "active": "Aktiv & Sport", "special": "Reise & Speziell" },
            "daily-errands": "Tägliche Erledigungen", "friends-gathering": "Treffen mit Freunden", "weekend-brunch": "Wochenend-Brunch", "coffee-date": "Kaffeetrinken", "shopping": "Einkaufen", "walk": "Spaziergang", "office-day": "Tag im Büro", "business-meeting": "Geschäftstreffen", "business-lunch": "Geschäftsessen", "networking": "Networking-Event", "university": "Universität / Vorlesung", "wedding": "Hochzeit", "special-event": "Besonderes Ereignis", "celebration": "Feier", "formal-dinner": "Formelles Abendessen", "dinner-date": "Dinner-Date", "birthday-party": "Geburtstagsfeier", "concert": "Konzert", "night-out": "Ausgehen", "house-party": "Hausparty", "gym": "Fitnessstudio / Training", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Outdoor-Sport", "hiking": "Wandern", "travel": "Reisen", "weekend-getaway": "Wochenendausflug", "holiday": "Urlaub", "festival": "Festival", "sightseeing": "Sightseeing"
        }
    },
    "id": {
        "colors": {
            "white": "Putih", "gray": "Abu-abu", "fume": "Arang", "black": "Hitam", "cream": "Krem", "beige": "Beige", "tan": "Cokelat muda", "cinnamon": "Kayu Manis", "earth": "Tanah", "chestnut": "Kastanye", "plum": "Plum", "khaki": "Khaki", "lemon": "Lemon", "yellow": "Kuning", "gold": "Emas", "mustard": "Mustard", "peach": "Peach", "apricot": "Aprikot", "salmon": "Salmon", "orange": "Oranye", "dusty-pink": "Dusty Rose", "coral": "Karang", "pomegranate-red": "Delima", "red": "Merah", "cherry-red": "Ceri", "dark-red": "Burgundy", "pink": "Pink", "fuchsia": "Fuchsia", "lilac": "Lila", "lavender": "Lavender", "violet": "Violet", "purple": "Ungu", "ice-blue": "Biru Es", "turquoise": "Pirus", "blue": "Biru", "saxony-blue": "Biru Royal", "navy": "Navy", "mint": "Mint", "water-green": "Hijau Aqua", "grass-green": "Hijau Rumput", "emerald": "Zamrud", "green": "Hijau", "olive": "Zaitun", "silver": "Perak", "bronze": "Perunggu", "leopard": "Leopard", "zebra": "Zebra", "snakeskin": "Kulit Ular", "striped": "Bergaris", "plaid": "Kotak-kotak", "floral": "Bunga", "polka-dot": "Polkadot"
        },
        "categories": {
            "top": "Atasan", "t-shirt": "Kaos", "blouse": "Blus", "shirt": "Kemeja", "sweater": "Sweater", "pullover": "Pullover", "sweatshirt": "Sweatshirt", "hoodie": "Hoodie", "track-top": "Jaket Olahraga", "crop-top": "Crop Top", "tank-top": "Tank Top", "bodysuit": "Bodysuit", "vest": "Rompi", "tunic": "Tunik", "bralette": "Bralette", "bottom": "Bawahan", "jeans": "Jeans", "trousers": "Celana Panjang", "linen-trousers": "Celana Linen", "leggings": "Legging", "track-bottom": "Celana Olahraga", "mini-skirt": "Rok Mini", "midi-skirt": "Rok Midi", "long-skirt": "Rok Panjang", "denim-shorts": "Celana Pendek Denim", "fabric-shorts": "Celana Pendek Kain", "athletic-shorts": "Celana Pendek Atletik", "bermuda-shorts": "Celana Bermuda", "capri-pants": "Celana Capri", "dresses-jumpsuits": "Gaun & Jumpsuit", "casual-dress": "Gaun Kasual", "evening-dress": "Gaun Malam", "sporty-dress": "Gaun Sporty", "modest-dress": "Gaun Sopan", "modest-evening-dress": "Gaun Malam Sopan", "jumpsuit": "Jumpsuit", "romper": "Romper", "outerwear": "Pakaian Luar", "puffer-coat": "Mantel Puffer", "raincoat": "Jas Hujan", "denim-jacket": "Jaket Denim", "leather-jacket": "Jaket Kulit", "fabric-jacket": "Jaket Kain", "bomber-jacket": "Jaket Bomber", "overcoat": "Mantel", "coat": "Mantel", "trenchcoat": "Trench Coat", "blazer": "Blazer", "cardigan": "Kardigan", "abaya": "Abaya", "shoes": "Sepatu", "sneakers": "Sneakers", "casual-sport-shoes": "Sepatu Olahraga Kasual", "heels": "Sepatu Hak Tinggi", "boots": "Sepatu Bot", "tall-boots": "Sepatu Bot Tinggi", "flats": "Sepatu Datar", "loafers": "Loafers", "bootie": "Bootie", "sandals": "Sandal", "slippers": "Sandal", "classic-shoes": "Sepatu Klasik", "bags": "Tas", "handbag": "Tas Tangan", "backpack": "Ransel", "shoulder-bag": "Tas Bahu", "briefcase": "Tas Kerja", "crossbody-bag": "Tas Selempang", "accessories": "Aksesori", "necklace": "Kalung", "earrings": "Anting-anting", "ring": "Cincin", "bracelet": "Gelang", "scarf": "Syal", "hijab": "Jilbab", "shawl": "Selendang", "sunglasses": "Kacamata Hitam", "belt": "Ikat Pinggang", "hat": "Topi", "watch": "Jam Tangan", "tie": "Dasi", "suits": "Setelan", "suit-jacket": "Jas", "suit-trousers": "Celana Jas", "tuxedo": "Tuksedo", "polo-shirt": "Kaos Polo"
        },
        "occasions": {
            "categories": { "casual": "Kasual", "work": "Kerja & Profesional", "formal": "Perayaan & Formal", "social": "Sosial", "active": "Aktif & Olahraga", "special": "Perjalanan & Khusus" },
            "daily-errands": "Urusan Harian", "friends-gathering": "Kumpul Teman", "weekend-brunch": "Brunch Akhir Pekan", "coffee-date": "Kencan Kopi", "shopping": "Belanja", "walk": "Jalan-jalan", "office-day": "Hari di Kantor", "business-meeting": "Pertemuan Bisnis", "business-lunch": "Makan Siang Bisnis", "networking": "Acara Jaringan", "university": "Universitas / Kelas", "wedding": "Pernikahan", "special-event": "Acara Khusus", "celebration": "Perayaan", "formal-dinner": "Makan Malam Formal", "dinner-date": "Kencan Makan Malam", "birthday-party": "Pesta Ulang Tahun", "concert": "Konser", "night-out": "Keluar Malam", "house-party": "Pesta di Rumah", "gym": "Gym / Kebugaran", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Olahraga Luar Ruangan", "hiking": "Mendaki", "travel": "Bepergian", "weekend-getaway": "Liburan Akhir Pekan", "holiday": "Liburan", "festival": "Festival", "sightseeing": "Jalan-jalan"
        }
    },
    "it": {
        "colors": {
            "white": "Bianco", "gray": "Grigio", "fume": "Antracite", "black": "Nero", "cream": "Crema", "beige": "Beige", "tan": "Marrone chiaro", "cinnamon": "Cannella", "earth": "Terra", "chestnut": "Castagna", "plum": "Prugna", "khaki": "Cachi", "lemon": "Limone", "yellow": "Giallo", "gold": "Oro", "mustard": "Senape", "peach": "Pesca", "apricot": "Albicocca", "salmon": "Salmone", "orange": "Arancione", "dusty-pink": "Rosa antico", "coral": "Corallo", "pomegranate-red": "Melograno", "red": "Rosso", "cherry-red": "Ciliegia", "dark-red": "Bordeaux", "pink": "Rosa", "fuchsia": "Fucsia", "lilac": "Lilla", "lavender": "Lavanda", "violet": "Viola", "purple": "Viola", "ice-blue": "Blu ghiaccio", "turquoise": "Turchese", "blue": "Blu", "saxony-blue": "Blu reale", "navy": "Blu scuro", "mint": "Menta", "water-green": "Verde acqua", "grass-green": "Verde erba", "emerald": "Smeraldo", "green": "Verde", "olive": "Oliva", "silver": "Argento", "bronze": "Bronzo", "leopard": "Leopardo", "zebra": "Zebra", "snakeskin": "Pelle di serpente", "striped": "A righe", "plaid": "Scozzese", "floral": "Floreale", "polka-dot": "A pois"
        },
        "categories": {
            "top": "Soprabiti", "t-shirt": "T-Shirt", "blouse": "Camicetta", "shirt": "Camicia", "sweater": "Maglione", "pullover": "Pullover", "sweatshirt": "Felpa", "hoodie": "Felpa con cappuccio", "track-top": "Giacca da tuta", "crop-top": "Crop Top", "tank-top": "Canottiera", "bodysuit": "Body", "vest": "Gilet", "tunic": "Tunica", "bralette": "Bralette", "bottom": "Pantaloni e gonne", "jeans": "Jeans", "trousers": "Pantaloni", "linen-trousers": "Pantaloni di lino", "leggings": "Leggings", "track-bottom": "Pantaloni da tuta", "mini-skirt": "Minigonna", "midi-skirt": "Gonna midi", "long-skirt": "Gonna lunga", "denim-shorts": "Pantaloncini di jeans", "fabric-shorts": "Pantaloncini di tessuto", "athletic-shorts": "Pantaloncini sportivi", "bermuda-shorts": "Bermuda", "capri-pants": "Pantaloni capri", "dresses-jumpsuits": "Abiti e Tute", "casual-dress": "Abito casual", "evening-dress": "Abito da sera", "sporty-dress": "Abito sportivo", "modest-dress": "Abito modesto", "modest-evening-dress": "Abito da sera modesto", "jumpsuit": "Tuta intera", "romper": "Pagliaccetto", "outerwear": "Capispalla", "puffer-coat": "Piumino", "raincoat": "Impermeabile", "denim-jacket": "Giacca di jeans", "leather-jacket": "Giacca di pelle", "fabric-jacket": "Giacca di tessuto", "bomber-jacket": "Bomber", "overcoat": "Soprabito", "coat": "Cappotto", "trenchcoat": "Trench", "blazer": "Blazer", "cardigan": "Cardigan", "abaya": "Abaya", "shoes": "Scarpe", "sneakers": "Sneakers", "casual-sport-shoes": "Scarpe sportive casual", "heels": "Tacchi", "boots": "Stivali", "tall-boots": "Stivali alti", "flats": "Ballerine", "loafers": "Mocassini", "bootie": "Stivaletto", "sandals": "Sandali", "slippers": "Pantofole", "classic-shoes": "Scarpe classiche", "bags": "Borse", "handbag": "Borsa a mano", "backpack": "Zaino", "shoulder-bag": "Borsa a tracolla", "briefcase": "Valigetta", "crossbody-bag": "Borsa a tracolla", "accessories": "Accessori", "necklace": "Collana", "earrings": "Orecchini", "ring": "Anello", "bracelet": "Braccialetto", "scarf": "Sciarpa", "hijab": "Hijab", "shawl": "Scialle", "sunglasses": "Occhiali da sole", "belt": "Cintura", "hat": "Cappello", "watch": "Orologio", "tie": "Cravatta", "suits": "Abiti", "suit-jacket": "Giacca da abito", "suit-trousers": "Pantaloni da abito", "tuxedo": "Smoking", "polo-shirt": "Polo"
        },
        "occasions": {
            "categories": { "casual": "Casual", "work": "Lavoro e Professionale", "formal": "Celebrazione e Formale", "social": "Sociale", "active": "Attivo e Sportivo", "special": "Viaggi e Speciale" },
            "daily-errands": "Commissioni quotidiane", "friends-gathering": "Incontro con amici", "weekend-brunch": "Brunch del fine settimana", "coffee-date": "Caffè", "shopping": "Shopping", "walk": "Una passeggiata", "office-day": "Giornata in ufficio", "business-meeting": "Riunione di lavoro", "business-lunch": "Pranzo di lavoro", "networking": "Evento di networking", "university": "Università / Lezione", "wedding": "Matrimonio", "special-event": "Evento speciale", "celebration": "Celebrazione", "formal-dinner": "Cena formale", "dinner-date": "Cena romantica", "birthday-party": "Festa di compleanno", "concert": "Concerto", "night-out": "Serata fuori", "house-party": "Festa in casa", "gym": "Palestra / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Sport all'aperto", "hiking": "Escursionismo", "travel": "Viaggio", "weekend-getaway": "Gita del fine settimana", "holiday": "Vacanza", "festival": "Festival", "sightseeing": "Visita turistica"
        }
    },
    "bg": {
        "colors": {
            "white": "Бяло", "gray": "Сиво", "fume": "Въглен", "black": "Черно", "cream": "Кремаво", "beige": "Бежово", "tan": "Светлокафяво", "cinnamon": "Канела", "earth": "Земно", "chestnut": "Кестеняво", "plum": "Слива", "khaki": "Каки", "lemon": "Лимон", "yellow": "Жълто", "gold": "Златно", "mustard": "Горчица", "peach": "Праскова", "apricot": "Кайсия", "salmon": "Сьомга", "orange": "Оранжево", "dusty-pink": "Пепел от рози", "coral": "Корал", "pomegranate-red": "Нар", "red": "Червено", "cherry-red": "Череша", "dark-red": "Бордо", "pink": "Розово", "fuchsia": "Фуксия", "lilac": "Люляк", "lavender": "Лавандула", "violet": "Виолетово", "purple": "Лилаво", "ice-blue": "Ледено синьо", "turquoise": "Тюркоаз", "blue": "Синьо", "saxony-blue": "Кралско синьо", "navy": "Тъмносиньо", "mint": "Мента", "water-green": "Аква зелено", "grass-green": "Тревно зелено", "emerald": "Изумруд", "green": "Зелено", "olive": "Маслина", "silver": "Сребърно", "bronze": "Бронзово", "leopard": "Леопард", "zebra": "Зебра", "snakeskin": "Змийска кожа", "striped": "Райе", "plaid": "Каре", "floral": "Флорален", "polka-dot": "На точки"
        },
        "categories": {
            "top": "Горнища", "t-shirt": "Тениска", "blouse": "Блуза", "shirt": "Риза", "sweater": "Пуловер", "pullover": "Пуловер", "sweatshirt": "Суитшърт", "hoodie": "Худи", "track-top": "Спортно горнище", "crop-top": "Кроп топ", "tank-top": "Потник", "bodysuit": "Боди", "vest": "Елек", "tunic": "Туника", "bralette": "Бралет", "bottom": "Долнища", "jeans": "Дънки", "trousers": "Панталони", "linen-trousers": "Ленени панталони", "leggings": "Клин", "track-bottom": "Спортен панталон", "mini-skirt": "Мини пола", "midi-skirt": "Миди пола", "long-skirt": "Дълга пола", "denim-shorts": "Дънкови шорти", "fabric-shorts": "Платнени шорти", "athletic-shorts": "Спортни шорти", "bermuda-shorts": "Бермуди", "capri-pants": "Капри панталони", "dresses-jumpsuits": "Рокли и гащеризони", "casual-dress": "Ежедневна рокля", "evening-dress": "Вечерна рокля", "sporty-dress": "Спортна рокля", "modest-dress": "Скромна рокля", "modest-evening-dress": "Скромна вечерна рокля", "jumpsuit": "Гащеризон", "romper": "Къс гащеризон", "outerwear": "Връхни дрехи", "puffer-coat": "Пухено яке", "raincoat": "Дъждобран", "denim-jacket": "Дънково яке", "leather-jacket": "Кожено яке", "fabric-jacket": "Платнено яке", "bomber-jacket": "Бомбър яке", "overcoat": "Палто", "coat": "Палто", "trenchcoat": "Тренчкот", "blazer": "Блейзър", "cardigan": "Жилетка", "abaya": "Абая", "shoes": "Обувки", "sneakers": "Маратонки", "casual-sport-shoes": "Ежедневни спортни обувки", "heels": "Токчета", "boots": "Боти", "tall-boots": "Ботуши", "flats": "Равни обувки", "loafers": "Мокасини", "bootie": "Боти", "sandals": "Сандали", "slippers": "Чехли", "classic-shoes": "Класически обувки", "bags": "Чанти", "handbag": "Ръчна чанта", "backpack": "Раница", "shoulder-bag": "Чанта за рамо", "briefcase": "Куфарче", "crossbody-bag": "Чанта през рамо", "accessories": "Аксесоари", "necklace": "Колие", "earrings": "Обеци", "ring": "Пръстен", "bracelet": "Гривна", "scarf": "Шал", "hijab": "Хиджаб", "shawl": "Шал", "sunglasses": "Слънчеви очила", "belt": "Колан", "hat": "Шапка", "watch": "Часовник", "tie": "Вратовръзка", "suits": "Костюми", "suit-jacket": "Сако", "suit-trousers": "Панталон за костюм", "tuxedo": "Смокинг", "polo-shirt": "Поло риза"
        },
        "occasions": {
            "categories": { "casual": "Ежедневни", "work": "Работни и професионални", "formal": "Празнични и официални", "social": "Социални", "active": "Активни и спортни", "special": "Пътувания и специални" },
            "daily-errands": "Ежедневни задачи", "friends-gathering": "Събиране с приятели", "weekend-brunch": "Брънч през уикенда", "coffee-date": "Кафе", "shopping": "Пазаруване", "walk": "Разходка", "office-day": "Ден в офиса", "business-meeting": "Бизнес среща", "business-lunch": "Бизнес обяд", "networking": "Събитие за нетуъркинг", "university": "Университет / Лекция", "wedding": "Сватба", "special-event": "Специално събитие", "celebration": "Празненство", "formal-dinner": "Официална вечеря", "dinner-date": "Вечеря", "birthday-party": "Рожден ден", "concert": "Концерт", "night-out": "Излизане вечер", "house-party": "Домашно парти", "gym": "Фитнес / Тренировка", "yoga-pilates": "Йога / Пилатес", "outdoor-sports": "Спортове на открито", "hiking": "Туризъм", "travel": "Пътуване", "weekend-getaway": "Уикенд бягство", "holiday": "Почивка", "festival": "Фестивал", "sightseeing": "Разглеждане на забележителности"
        }
    },
    "zh": {
        "colors": {
            "white": "白色", "gray": "灰色", "fume": "炭灰色", "black": "黑色", "cream": "奶油色", "beige": "米色", "tan": "棕褐色", "cinnamon": "肉桂色", "earth": "土色", "chestnut": "栗色", "plum": "李子色", "khaki": "卡其色", "lemon": "柠檬黄", "yellow": "黄色", "gold": "金色", "mustard": "芥末黄", "peach": "桃色", "apricot": "杏色", "salmon": "鲑鱼色", "orange": "橙色", "dusty-pink": "灰玫瑰色", "coral": "珊瑚色", "pomegranate-red": "石榴红", "red": "红色", "cherry-red": "樱桃红", "dark-red": "酒红色", "pink": "粉红色", "fuchsia": "紫红色", "lilac": "丁香紫", "lavender": "薰衣草紫", "violet": "紫罗兰色", "purple": "紫色", "ice-blue": "冰蓝色", "turquoise": "绿松石色", "blue": "蓝色", "saxony-blue": "宝蓝色", "navy": "海军蓝", "mint": "薄荷绿", "water-green": "水绿色", "grass-green": "草绿色", "emerald": "翡翠绿", "green": "绿色", "olive": "橄榄绿", "silver": "银色", "bronze": "青铜色", "leopard": "豹纹", "zebra": "斑马纹", "snakeskin": "蛇皮纹", "striped": "条纹", "plaid": "格子", "floral": "花卉", "polka-dot": "波点"
        },
        "categories": {
            "top": "上装", "t-shirt": "T恤", "blouse": "罩衫", "shirt": "衬衫", "sweater": "毛衣", "pullover": "套头衫", "sweatshirt": "卫衣", "hoodie": "连帽衫", "track-top": "运动上衣", "crop-top": "露脐上衣", "tank-top": "背心", "bodysuit": "连体衣", "vest": "马甲", "tunic": "束腰外衣", "bralette": "文胸式上衣", "bottom": "下装", "jeans": "牛仔裤", "trousers": "长裤", "linen-trousers": "亚麻裤", "leggings": "打底裤", "track-bottom": "运动裤", "mini-skirt": "迷你裙", "midi-skirt": "中长裙", "long-skirt": "长裙", "denim-shorts": "牛仔短裤", "fabric-shorts": "布料短裤", "athletic-shorts": "运动短裤", "bermuda-shorts": "百慕大短裤", "capri-pants": "七分裤", "dresses-jumpsuits": "连衣裙和连身裤", "casual-dress": "休闲连衣裙", "evening-dress": "晚礼服", "sporty-dress": "运动连衣裙", "modest-dress": "端庄连衣裙", "modest-evening-dress": "端庄晚礼服", "jumpsuit": "连身裤", "romper": "连身短裤", "outerwear": "外套", "puffer-coat": "羽绒服", "raincoat": "雨衣", "denim-jacket": "牛仔夹克", "leather-jacket": "皮夹克", "fabric-jacket": "布料夹克", "bomber-jacket": "飞行员夹克", "overcoat": "大衣", "coat": "外套", "trenchcoat": "风衣", "blazer": "西装外套", "cardigan": "开衫", "abaya": "长袍", "shoes": "鞋子", "sneakers": "运动鞋", "casual-sport-shoes": "休闲运动鞋", "heels": "高跟鞋", "boots": "靴子", "tall-boots": "高筒靴", "flats": "平底鞋", "loafers": "乐福鞋", "bootie": "短靴", "sandals": "凉鞋", "slippers": "拖鞋", "classic-shoes": "经典鞋", "bags": "包袋", "handbag": "手提包", "backpack": "背包", "shoulder-bag": "单肩包", "briefcase": "公文包", "crossbody-bag": "斜挎包", "accessories": "配饰", "necklace": "项链", "earrings": "耳环", "ring": "戒指", "bracelet": "手镯", "scarf": "围巾", "hijab": "头巾", "shawl": "披肩", "sunglasses": "太阳镜", "belt": "腰带", "hat": "帽子", "watch": "手表", "tie": "领带", "suits": "西装", "suit-jacket": "西装上衣", "suit-trousers": "西裤", "tuxedo": "晚礼服", "polo-shirt": "Polo衫"
        },
        "occasions": {
            "categories": { "casual": "休闲", "work": "工作与专业", "formal": "庆典与正式", "social": "社交", "active": "运动", "special": "旅行与特殊" },
            "daily-errands": "日常 errands", "friends-gathering": "朋友聚会", "weekend-brunch": "周末早午餐", "coffee-date": "咖啡约会", "shopping": "购物", "walk": "散步", "office-day": "办公室日", "business-meeting": "商务会议", "business-lunch": "商务午餐", "networking": "社交活动", "university": "大学/上课", "wedding": "婚礼", "special-event": "特殊活动", "celebration": "庆祝活动", "formal-dinner": "正式晚宴", "dinner-date": "晚餐约会", "birthday-party": "生日派对", "concert": "音乐会", "night-out": "夜间外出", "house-party": "家庭派对", "gym": "健身房/健身", "yoga-pilates": "瑜伽/普拉提", "outdoor-sports": "户外运动", "hiking": "徒步", "travel": "旅行", "weekend-getaway": "周末短途旅行", "holiday": "假日", "festival": "节日", "sightseeing": "观光"
        }
    },
    "pt": {
        "colors": {
            "white": "Branco", "gray": "Cinza", "fume": "Carvão", "black": "Preto", "cream": "Creme", "beige": "Bege", "tan": "Bronzeado", "cinnamon": "Canela", "earth": "Terra", "chestnut": "Castanho", "plum": "Ameixa", "khaki": "Cáqui", "lemon": "Limão", "yellow": "Amarelo", "gold": "Dourado", "mustard": "Mostarda", "peach": "Pêssego", "apricot": "Damasco", "salmon": "Salmão", "orange": "Laranja", "dusty-pink": "Rosa antigo", "coral": "Coral", "pomegranate-red": "Romã", "red": "Vermelho", "cherry-red": "Cereja", "dark-red": "Borgonha", "pink": "Rosa", "fuchsia": "Fúcsia", "lilac": "Lilás", "lavender": "Lavanda", "violet": "Violeta", "purple": "Roxo", "ice-blue": "Azul-gelo", "turquoise": "Turquesa", "blue": "Azul", "saxony-blue": "Azul-royal", "navy": "Azul-marinho", "mint": "Menta", "water-green": "Verde-água", "grass-green": "Verde-grama", "emerald": "Esmeralda", "green": "Verde", "olive": "Oliva", "silver": "Prata", "bronze": "Bronze", "leopard": "Leopardo", "zebra": "Zebra", "snakeskin": "Pele de cobra", "striped": "Listrado", "plaid": "Xadrez", "floral": "Floral", "polka-dot": "Poá"
        },
        "categories": {
            "top": "Parte de Cima", "t-shirt": "Camiseta", "blouse": "Blusa", "shirt": "Camisa", "sweater": "Suéter", "pullover": "Pulôver", "sweatshirt": "Moletom", "hoodie": "Moletom com Capuz", "track-top": "Jaqueta Esportiva", "crop-top": "Top Cropped", "tank-top": "Regata", "bodysuit": "Body", "vest": "Colete", "tunic": "Túnica", "bralette": "Bralette", "bottom": "Parte de Baixo", "jeans": "Jeans", "trousers": "Calças", "linen-trousers": "Calças de Linho", "leggings": "Leggings", "track-bottom": "Calça Esportiva", "mini-skirt": "Minissaia", "midi-skirt": "Saia Midi", "long-skirt": "Saia Longa", "denim-shorts": "Shorts Jeans", "fabric-shorts": "Shorts de Tecido", "athletic-shorts": "Shorts Esportivos", "bermuda-shorts": "Bermudas", "capri-pants": "Calças Capri", "dresses-jumpsuits": "Vestidos e Macacões", "casual-dress": "Vestido Casual", "evening-dress": "Vestido de Festa", "sporty-dress": "Vestido Esportivo", "modest-dress": "Vestido Comportado", "modest-evening-dress": "Vestido de Festa Comportado", "jumpsuit": "Macacão", "romper": "Macaquinho", "outerwear": "Agasalhos", "puffer-coat": "Casaco Acolchoado", "raincoat": "Capa de Chuva", "denim-jacket": "Jaqueta Jeans", "leather-jacket": "Jaqueta de Couro", "fabric-jacket": "Jaqueta de Tecido", "bomber-jacket": "Jaqueta Bomber", "overcoat": "Sobretudo", "coat": "Casaco", "trenchcoat": "Trench Coat", "blazer": "Blazer", "cardigan": "Cardigã", "abaya": "Abaya", "shoes": "Sapatos", "sneakers": "Tênis", "casual-sport-shoes": "Tênis Esportivo Casual", "heels": "Saltos", "boots": "Botas", "tall-boots": "Botas de Cano Alto", "flats": "Sapatilhas", "loafers": "Mocassins", "bootie": "Bota de Cano Curto", "sandals": "Sandálias", "slippers": "Chinelos", "classic-shoes": "Sapatos Clássicos", "bags": "Bolsas", "handbag": "Bolsa de Mão", "backpack": "Mochila", "shoulder-bag": "Bolsa de Ombro", "briefcase": "Pasta", "crossbody-bag": "Bolsa Transversal", "accessories": "Acessórios", "necklace": "Colar", "earrings": "Brincos", "ring": "Anel", "bracelet": "Pulseira", "scarf": "Cachecol", "hijab": "Hijab", "shawl": "Xale", "sunglasses": "Óculos de Sol", "belt": "Cinto", "hat": "Chapéu", "watch": "Relógio", "tie": "Gravata", "suits": "Ternos", "suit-jacket": "Paletó", "suit-trousers": "Calças de Terno", "tuxedo": "Smoking", "polo-shirt": "Camisa Polo"
        },
        "occasions": {
            "categories": { "casual": "Casual", "work": "Trabalho e Profissional", "formal": "Celebração e Formal", "social": "Social", "active": "Ativo e Esportivo", "special": "Viagem e Especial" },
            "daily-errands": "Tarefas Diárias", "friends-gathering": "Encontro com Amigos", "weekend-brunch": "Brunch de Fim de Semana", "coffee-date": "Café", "shopping": "Compras", "walk": "Um Passeio", "office-day": "Dia no Escritório", "business-meeting": "Reunião de Negócios", "business-lunch": "Almoço de Negócios", "networking": "Evento de Networking", "university": "Universidade / Aula", "wedding": "Casamento", "special-event": "Evento Especial", "celebration": "Celebração", "formal-dinner": "Jantar Formal", "dinner-date": "Encontro para Jantar", "birthday-party": "Festa de Aniversário", "concert": "Concerto", "night-out": "Saída à Noite", "house-party": "Festa em Casa", "gym": "Academia / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Esportes ao Ar Livre", "hiking": "Trilha", "travel": "Viagem", "weekend-getaway": "Viagem de Fim de Semana", "holiday": "Feriado", "festival": "Festival", "sightseeing": "Passeio Turístico"
        }
    },
    "el": {
        "colors": {
            "white": "Λευκό", "gray": "Γκρι", "fume": "Ανθρακί", "black": "Μαύρο", "cream": "Κρεμ", "beige": "Μπεζ", "tan": "Καφέ ανοιχτό", "cinnamon": "Κανελί", "earth": "Γήινο", "chestnut": "Καστανό", "plum": "Δαμασκηνί", "khaki": "Χακί", "lemon": "Λεμονί", "yellow": "Κίτρινο", "gold": "Χρυσό", "mustard": "Μουσταρδί", "peach": "Ροδακινί", "apricot": "Βερικοκί", "salmon": "Σομόν", "orange": "Πορτοκαλί", "dusty-pink": "Σάπιο μήλο", "coral": "Κοραλί", "pomegranate-red": "Ροδί", "red": "Κόκκινο", "cherry-red": "Κερασί", "dark-red": "Βουργουνδί", "pink": "Ροζ", "fuchsia": "Φούξια", "lilac": "Λιλά", "lavender": "Λεβάντα", "violet": "Βιολετί", "purple": "Μωβ", "ice-blue": "Γαλάζιο του πάγου", "turquoise": "Τυρκουάζ", "blue": "Μπλε", "saxony-blue": "Βασιλικό μπλε", "navy": "Ναυτικό μπλε", "mint": "Μέντα", "water-green": "Πράσινο του νερού", "grass-green": "Πράσιно του γρασιδιού", "emerald": "Σμαραγδί", "green": "Πράσινο", "olive": "Λαδί", "silver": "Ασημί", "bronze": "Μπρονζέ", "leopard": "Λεοπάρ", "zebra": "Ζέβρα", "snakeskin": "Φιδέ", "striped": "Ριγέ", "plaid": "Καρό", "floral": "Φλοράλ", "polka-dot": "Πουά"
        },
        "categories": {
            "top": "Μπλούζες", "t-shirt": "T-Shirt", "blouse": "Μπλούζα", "shirt": "Πουκάμισο", "sweater": "Πουλόβερ", "pullover": "Πουλόβερ", "sweatshirt": "Φούτερ", "hoodie": "Φούτερ με κουκούλα", "track-top": "Αθλητική ζακέτα", "crop-top": "Crop Top", "tank-top": "Φανελάκι", "bodysuit": "Κορμάκι", "vest": "Γιλέκο", "tunic": "Τουνίκ", "bralette": "Μπραλέτ", "bottom": "Παντελόνια", "jeans": "Τζιν", "trousers": "Παντελόνι", "linen-trousers": "Λινό παντελόνι", "leggings": "Κολάν", "track-bottom": "Αθλητικό παντελόνι", "mini-skirt": "Μίνι φούστα", "midi-skirt": "Μίντι φούστα", "long-skirt": "Μακριά φούστα", "denim-shorts": "Τζιν σορτς", "fabric-shorts": "Υφασμάτινο σορτς", "athletic-shorts": "Αθλητικό σορτς", "bermuda-shorts": "Βερμούδα", "capri-pants": "Παντελόνι κάπρι", "dresses-jumpsuits": "Φορέματα & Ολόσωμες Φόρμες", "casual-dress": "Καθημερινό φόρεμα", "evening-dress": "Βραδινό φόρεμα", "sporty-dress": "Αθλητικό φόρεμα", "modest-dress": "Σεμνό φόρεμα", "modest-evening-dress": "Σεμνό βραδινό φόρεμα", "jumpsuit": "Ολόσωμη φόρμα", "romper": "Romper", "outerwear": "Πανωφόρια", "puffer-coat": "Φουσκωτό μπουφάν", "raincoat": "Αδιάβροχο", "denim-jacket": "Τζιν μπουφάν", "leather-jacket": "Δερμάτινο μπουφάν", "fabric-jacket": "Υφασμάτινο μπουφάν", "bomber-jacket": "Bomber μπουφάν", "overcoat": "Παλτό", "coat": "Παλτό", "trenchcoat": "Καμπαρντίνα", "blazer": "Σακάκι", "cardigan": "Ζακέτα", "abaya": "Αμπάγια", "shoes": "Παπούτσια", "sneakers": "Αθλητικά παπούτσια", "casual-sport-shoes": "Casual αθλητικά παπούτσια", "heels": "Τακούνια", "boots": "Μπότες", "tall-boots": "Ψηλές μπότες", "flats": "Φλατ παπούτσια", "loafers": "Loafers", "bootie": "Μποτάκια", "sandals": "Σανδάλια", "slippers": "Παντόφλες", "classic-shoes": "Κλασικά παπούτσια", "bags": "Τσάντες", "handbag": "Τσάντα χειρός", "backpack": "Σακίδιο", "shoulder-bag": "Τσάντα ώμου", "briefcase": "Χαρτοφύλακας", "crossbody-bag": "Τσάντα χιαστί", "accessories": "Αξεσουάρ", "necklace": "Κολιέ", "earrings": "Σκουλαρίκια", "ring": "Δαχτυλίδι", "bracelet": "Βραχιόλι", "scarf": "Κασκόλ", "hijab": "Χιτζάμπ", "shawl": "Σάλι", "sunglasses": "Γυαλιά ηλίου", "belt": "Ζώνη", "hat": "Καπέλο", "watch": "Ρολόι", "tie": "Γραβάτα", "suits": "Κοστούμια", "suit-jacket": "Σακάκι κοστουμιού", "suit-trousers": "Παντελόνι κοστουμιού", "tuxedo": "Σμόκιν", "polo-shirt": "Μπλούζα πόλο"
        },
        "occasions": {
            "categories": { "casual": "Καθημερινές", "work": "Εργασία & Επαγγελματικές", "formal": "Εορταστικές & Επίσημες", "social": "Κοινωνικές", "active": "Δραστηριότητες & Αθλητισμός", "special": "Ταξίδια & Ειδικές" },
            "daily-errands": "Καθημερινές δουλειές", "friends-gathering": "Συνάντηση με φίλους", "weekend-brunch": "Brunch Σαββατοκύριακου", "coffee-date": "Καφές", "shopping": "Ψώνια", "walk": "Βόλτα", "office-day": "Μέρα στο γραφείο", "business-meeting": "Επαγγελματική συνάντηση", "business-lunch": "Επαγγελματικό γεύμα", "networking": "Εκδήλωση δικτύωσης", "university": "Πανεπιστήμιο / Μάθημα", "wedding": "Γάμος", "special-event": "Ειδική εκδήλωση", "celebration": "Γιορτή", "formal-dinner": "Επίσημο δείπνο", "dinner-date": "Ραντεβού για δείπνο", "birthday-party": "Πάρτι γενεθλίων", "concert": "Συναυλία", "night-out": "Νυχτερινή έξοδος", "house-party": "Πάρτι στο σπίτι", "gym": "Γυμναστήριο / Fitness", "yoga-pilates": "Γιόγκα / Πιλάτες", "outdoor-sports": "Υπαίθρια αθλήματα", "hiking": "Πεζοπορία", "travel": "Ταξίδι", "weekend-getaway": "Απόδραση Σαββατοκύριακου", "holiday": "Διακοπές", "festival": "Φεστιβάλ", "sightseeing": "Αξιοθέατα"
        }
    },
    "tl": {
        "colors": {
            "white": "Puti", "gray": "Abo", "fume": "Uling", "black": "Itim", "cream": "Krema", "beige": "Beige", "tan": "Tan", "cinnamon": "Kanela", "earth": "Lupa", "chestnut": "Kastanyas", "plum": "Plum", "khaki": "Khaki", "lemon": "Lemon", "yellow": "Dilaw", "gold": "Ginto", "mustard": "Mustasa", "peach": "Peach", "apricot": "Aprikot", "salmon": "Salmon", "orange": "Kahel", "dusty-pink": "Maalikabok na Rosas", "coral": "Coral", "pomegranate-red": "Granada", "red": "Pula", "cherry-red": "Seresa", "dark-red": "Burgundy", "pink": "Rosas", "fuchsia": "Fuchsia", "lilac": "Lila", "lavender": "Lavender", "violet": "Biyoleta", "purple": "Lila", "ice-blue": "Asul na Yelo", "turquoise": "Turkesa", "blue": "Asul", "saxony-blue": "Royal Blue", "navy": "Navy", "mint": "Mint", "water-green": "Aqua Green", "grass-green": "Damong Berde", "emerald": "Esmeralda", "green": "Berde", "olive": "Oliba", "silver": "Pilak", "bronze": "Tanso", "leopard": "Leopard", "zebra": "Zebra", "snakeskin": "Balat ng Ahas", "striped": "Guhitan", "plaid": "Plaid", "floral": "Bulaklakin", "polka-dot": "Polka Dot"
        },
        "categories": {
            "top": "Pang-itaas", "t-shirt": "T-Shirt", "blouse": "Blusa", "shirt": "Kamiseta", "sweater": "Sweater", "pullover": "Pullover", "sweatshirt": "Sweatshirt", "hoodie": "Hoodie", "track-top": "Track Top", "crop-top": "Crop Top", "tank-top": "Tank Top", "bodysuit": "Bodysuit", "vest": "Vest", "tunic": "Tunic", "bralette": "Bralette", "bottom": "Pang-ibaba", "jeans": "Maong", "trousers": "Pantalon", "linen-trousers": "Pantalon na Linen", "leggings": "Leggings", "track-bottom": "Track Bottom", "mini-skirt": "Mini Skirt", "midi-skirt": "Midi Skirt", "long-skirt": "Mahabang Palda", "denim-shorts": "Shorts na Maong", "fabric-shorts": "Shorts na Tela", "athletic-shorts": "Shorts na Pang-atletiko", "bermuda-shorts": "Bermuda Shorts", "capri-pants": "Capri Pants", "dresses-jumpsuits": "Mga Damit at Jumpsuit", "casual-dress": "Kaswal na Damit", "evening-dress": "Damit Panggabi", "sporty-dress": "Damit na Pampalakasan", "modest-dress": "Mahinhing Damit", "modest-evening-dress": "Mahinhing Damit Panggabi", "jumpsuit": "Jumpsuit", "romper": "Romper", "outerwear": "Panglabas na Kasuotan", "puffer-coat": "Puffer Coat", "raincoat": "Kapote", "denim-jacket": "Jacket na Maong", "leather-jacket": "Jacket na Balat", "fabric-jacket": "Jacket na Tela", "bomber-jacket": "Bomber Jacket", "overcoat": "Overcoat", "coat": "Coat", "trenchcoat": "Trenchcoat", "blazer": "Blazer", "cardigan": "Cardigan", "abaya": "Abaya", "shoes": "Sapatos", "sneakers": "Sneakers", "casual-sport-shoes": "Kaswal na Sapatos na Pampalakasan", "heels": "Takong", "boots": "Bota", "tall-boots": "Matataas na Bota", "flats": "Flats", "loafers": "Loafers", "bootie": "Bootie", "sandals": "Sandalyas", "slippers": "Tsinelas", "classic-shoes": "Klasikong Sapatos", "bags": "Mga Bag", "handbag": "Handbag", "backpack": "Backpack", "shoulder-bag": "Shoulder Bag", "briefcase": "Briefcase", "crossbody-bag": "Crossbody Bag", "accessories": "Mga Aksesorya", "necklace": "Kwintas", "earrings": "Hikaw", "ring": "Singsing", "bracelet": "Pulseras", "scarf": "Scarf", "hijab": "Hijab", "shawl": "Shawl", "sunglasses": "Salamin sa Araw", "belt": "Sinturon", "hat": "Sumbrero", "watch": "Relo", "tie": "Kurbata", "suits": "Mga Suit", "suit-jacket": "Suit Jacket", "suit-trousers": "Pantalon ng Suit", "tuxedo": "Tuxedo", "polo-shirt": "Polo Shirt"
        },
        "occasions": {
            "categories": { "casual": "Kaswal", "work": "Trabaho at Propesyonal", "formal": "Pagdiriwang at Pormal", "social": "Sosyal", "active": "Aktibo at Pampalakasan", "special": "Paglalakbay at Espesyal" },
            "daily-errands": "Pang-araw-araw na Gawain", "friends-gathering": "Pagtitipon ng mga Kaibigan", "weekend-brunch": "Brunch sa Weekend", "coffee-date": "Kape", "shopping": "Pamimili", "walk": "Isang Lakad", "office-day": "Araw sa Opisina", "business-meeting": "Pulong sa Negosyo", "business-lunch": "Tanghalian sa Negosyo", "networking": "Networking Event", "university": "Unibersidad / Klase", "wedding": "Kasal", "special-event": "Espesyal na Kaganapan", "celebration": "Pagdiriwang", "formal-dinner": "Pormal na Hapunan", "dinner-date": "Petsa ng Hapunan", "birthday-party": "Kaarawan", "concert": "Konsiyerto", "night-out": "Gabi sa Labas", "house-party": "Party sa Bahay", "gym": "Gym / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Panlabas na Palakasan", "hiking": "Pag-akyat ng Bundok", "travel": "Paglalakbay", "weekend-getaway": "Paglalakbay sa Weekend", "holiday": "Bakasyon", "festival": "Pista", "sightseeing": "Pamamasyal"
        }
    },
    "ar": {
        "colors": {
            "white": "أبيض", "gray": "رمادي", "fume": "فحمي", "black": "أسود", "cream": "كريمي", "beige": "بيج", "tan": "بني فاتح", "cinnamon": "قرفي", "earth": "ترابي", "chestnut": "كستنائي", "plum": "برقوقي", "khaki": "كاكي", "lemon": "ليموني", "yellow": "أصفر", "gold": "ذهبي", "mustard": "خردلي", "peach": "خوخي", "apricot": "مشمشي", "salmon": "سلموني", "orange": "برتقالي", "dusty-pink": "وردي مغبر", "coral": "مرجاني", "pomegranate-red": "أحمر رماني", "red": "أحمر", "cherry-red": "كرزي", "dark-red": "خمري", "pink": "وردي", "fuchsia": "فوشيا", "lilac": "ليلكي", "lavender": "خزامي", "violet": "بنفسجي", "purple": "أرجواني", "ice-blue": "أزرق ثلجي", "turquoise": "فيروزي", "blue": "أزرق", "saxony-blue": "أزرق ملكي", "navy": "كحلي", "mint": "نعناعي", "water-green": "أخضر مائي", "grass-green": "أخضر عشبي", "emerald": "زمردي", "green": "أخضر", "olive": "زيتوني", "silver": "فضي", "bronze": "برونزي", "leopard": "جلد الفهد", "zebra": "جلد الحمار الوحشي", "snakeskin": "جلد الثعبان", "striped": "مخطط", "plaid": "مربعات", "floral": "مُزهّر", "polka-dot": "منقط"
        },
        "categories": {
            "top": "ملابس علوية", "t-shirt": "تي شيرت", "blouse": "بلوزة", "shirt": "قميص", "sweater": "سترة", "pullover": "بلوفر", "sweatshirt": "سويت شيرت", "hoodie": "هودي", "track-top": "جاكيت رياضي", "crop-top": "توب قصير", "tank-top": "توب بدون أكمام", "bodysuit": "بودي سوت", "vest": "صديري", "tunic": "تونيك", "bralette": "براليت", "bottom": "ملابس سفلية", "jeans": "جينز", "trousers": "بنطلون", "linen-trousers": "بنطلون كتان", "leggings": "ليقنز", "track-bottom": "بنطلون رياضي", "mini-skirt": "تنورة قصيرة", "midi-skirt": "تنورة متوسطة الطول", "long-skirt": "تنورة طويلة", "denim-shorts": "شورت جينز", "fabric-shorts": "شورت قماش", "athletic-shorts": "شورت رياضي", "bermuda-shorts": "شورت برمودا", "capri-pants": "بنطلون كابري", "dresses-jumpsuits": "فساتين وجمبسوت", "casual-dress": "فستان كاجوال", "evening-dress": "فستان سهرة", "sporty-dress": "فستان رياضي", "modest-dress": "فستان محتشم", "modest-evening-dress": "فستان سهرة محتشم", "jumpsuit": "جمبسوت", "romper": "رومبر", "outerwear": "ملابس خارجية", "puffer-coat": "معطف منفوخ", "raincoat": "معطف واق من المطر", "denim-jacket": "جاكيت جينز", "leather-jacket": "جاكيت جلد", "fabric-jacket": "جاكيت قماش", "bomber-jacket": "جاكيت بومبر", "overcoat": "معطف طويل", "coat": "معطف", "trenchcoat": "معطف ترنش", "blazer": "بليزر", "cardigan": "كارديغان", "abaya": "عباءة", "shoes": "أحذية", "sneakers": "سنيكرز", "casual-sport-shoes": "أحذية رياضية كاجوال", "heels": "كعب عالي", "boots": "بوت", "tall-boots": "بوت طويل", "flats": "حذاء مسطح", "loafers": "لوفر", "bootie": "بوتي", "sandals": "صندل", "slippers": "شبشب", "classic-shoes": "حذاء كلاسيكي", "bags": "حقائب", "handbag": "حقيبة يد", "backpack": "حقيبة ظهر", "shoulder-bag": "حقيبة كتف", "briefcase": "حقيبة عمل", "crossbody-bag": "حقيبة كروس", "accessories": "إكسسوارات", "necklace": "قلادة", "earrings": "أقراط", "ring": "خاتم", "bracelet": "سوار", "scarf": "وشاح", "hijab": "حجاب", "shawl": "شال", "sunglasses": "نظارات شمسية", "belt": "حزام", "hat": "قبعة", "watch": "ساعة", "tie": "ربطة عنق", "suits": "بدل", "suit-jacket": "جاكيت بدلة", "suit-trousers": "بنطلون بدلة", "tuxedo": "توكسيدو", "polo-shirt": "قميص بولو"
        },
        "occasions": {
            "categories": { "casual": "غير رسمي", "work": "عمل ومهني", "formal": "احتفال ورسمي", "social": "اجتماعي", "active": "نشاط ورياضة", "special": "سفر وخاص" },
            "daily-errands": "مشاوير يومية", "friends-gathering": "لقاء أصدقاء", "weekend-brunch": "فطور وغداء عطلة نهاية الأسبوع", "coffee-date": "موعد قهوة", "shopping": "تسوق", "walk": "نزهة", "office-day": "يوم في المكتب", "business-meeting": "اجتماع عمل", "business-lunch": "غداء عمل", "networking": "فعالية تواصل", "university": "جامعة / فصل دراسي", "wedding": "حفل زفاف", "special-event": "مناسبة خاصة", "celebration": "احتفال", "formal-dinner": "عشاء رسمي", "dinner-date": "موعد عشاء", "birthday-party": "حفلة عيد ميلاد", "concert": "حفل موسيقي", "night-out": "سهرة بالخارج", "house-party": "حفلة منزلية", "gym": "صالة رياضية / لياقة بدنية", "yoga-pilates": "يوجا / بيلاتيس", "outdoor-sports": "رياضات خارجية", "hiking": "تنزه جبلي", "travel": "سفر", "weekend-getaway": "عطلة نهاية الأسبوع", "holiday": "إجازة", "festival": "مهرجان", "sightseeing": "مشاهدة معالم"
        }
    },
    "fr": {
        "colors": {
            "white": "Blanc", "gray": "Gris", "fume": "Charbon", "black": "Noir", "cream": "Crème", "beige": "Beige", "tan": "Fauve", "cinnamon": "Cannelle", "earth": "Terre", "chestnut": "Châtaigne", "plum": "Prune", "khaki": "Kaki", "lemon": "Citron", "yellow": "Jaune", "gold": "Or", "mustard": "Moutarde", "peach": "Pêche", "apricot": "Abricot", "salmon": "Saumon", "orange": "Orange", "dusty-pink": "Vieux rose", "coral": "Corail", "pomegranate-red": "Grenade", "red": "Rouge", "cherry-red": "Cerise", "dark-red": "Bordeaux", "pink": "Rose", "fuchsia": "Fuchsia", "lilac": "Lilas", "lavender": "Lavande", "violet": "Violet", "purple": "Violet", "ice-blue": "Bleu glacier", "turquoise": "Turquoise", "blue": "Bleu", "saxony-blue": "Bleu roi", "navy": "Bleu marine", "mint": "Menthe", "water-green": "Vert d'eau", "grass-green": "Vert gazon", "emerald": "Émeraude", "green": "Vert", "olive": "Olive", "silver": "Argent", "bronze": "Bronze", "leopard": "Léopard", "zebra": "Zèbre", "snakeskin": "Peau de serpent", "striped": "Rayé", "plaid": "Écossais", "floral": "Fleuri", "polka-dot": "À pois"
        },
        "categories": {
            "top": "Hauts", "t-shirt": "T-shirt", "blouse": "Blouse", "shirt": "Chemise", "sweater": "Pull", "pullover": "Pull-over", "sweatshirt": "Sweat-shirt", "hoodie": "Sweat à capuche", "track-top": "Haut de survêtement", "crop-top": "Crop top", "tank-top": "Débardeur", "bodysuit": "Body", "vest": "Gilet", "tunic": "Tunique", "bralette": "Bralette", "bottom": "Bas", "jeans": "Jean", "trousers": "Pantalon", "linen-trousers": "Pantalon en lin", "leggings": "Legging", "track-bottom": "Bas de survêtement", "mini-skirt": "Mini-jupe", "midi-skirt": "Jupe midi", "long-skirt": "Jupe longue", "denim-shorts": "Short en jean", "fabric-shorts": "Short en tissu", "athletic-shorts": "Short de sport", "bermuda-shorts": "Bermuda", "capri-pants": "Pantacourt", "dresses-jumpsuits": "Robes & Combinaisons", "casual-dress": "Robe décontractée", "evening-dress": "Robe de soirée", "sporty-dress": "Robe de sport", "modest-dress": "Robe pudique", "modest-evening-dress": "Robe de soirée pudique", "jumpsuit": "Combinaison", "romper": "Combi-short", "outerwear": "Vêtements d'extérieur", "puffer-coat": "Doudoune", "raincoat": "Imperméable", "denim-jacket": "Veste en jean", "leather-jacket": "Veste en cuir", "fabric-jacket": "Veste en tissu", "bomber-jacket": "Blouson aviateur", "overcoat": "Manteau", "coat": "Manteau", "trenchcoat": "Trench-coat", "blazer": "Blazer", "cardigan": "Cardigan", "abaya": "Abaya", "shoes": "Chaussures", "sneakers": "Baskets", "casual-sport-shoes": "Chaussures de sport décontractées", "heels": "Talons", "boots": "Bottes", "tall-boots": "Bottes hautes", "flats": "Chaussures plates", "loafers": "Mocassins", "bootie": "Bottine", "sandals": "Sandales", "slippers": "Pantoufles", "classic-shoes": "Chaussures classiques", "bags": "Sacs", "handbag": "Sac à main", "backpack": "Sac à dos", "shoulder-bag": "Sac en bandoulière", "briefcase": "Mallette", "crossbody-bag": "Sac bandoulière", "accessories": "Accessoires", "necklace": "Collier", "earrings": "Boucles d'oreilles", "ring": "Bague", "bracelet": "Bracelet", "scarf": "Écharpe", "hijab": "Hijab", "shawl": "Châle", "sunglasses": "Lunettes de soleil", "belt": "Ceinture", "hat": "Chapeau", "watch": "Montre", "tie": "Cravate", "suits": "Costumes", "suit-jacket": "Veste de costume", "suit-trousers": "Pantalon de costume", "tuxedo": "Smoking", "polo-shirt": "Polo"
        },
        "occasions": {
            "categories": { "casual": "Décontracté", "work": "Travail & Professionnel", "formal": "Célébration & Formel", "social": "Social", "active": "Actif & Sport", "special": "Voyage & Spécial" },
            "daily-errands": "Courses quotidiennes", "friends-gathering": "Rencontre entre amis", "weekend-brunch": "Brunch du week-end", "coffee-date": "Café", "shopping": "Shopping", "walk": "Une promenade", "office-day": "Journée au bureau", "business-meeting": "Réunion d'affaires", "business-lunch": "Déjeuner d'affaires", "networking": "Événement de réseautage", "university": "Université / Cours", "wedding": "Mariage", "special-event": "Événement spécial", "celebration": "Célébration", "formal-dinner": "Dîner formel", "dinner-date": "Dîner en amoureux", "birthday-party": "Fête d'anniversaire", "concert": "Concert", "night-out": "Soirée", "house-party": "Fête à la maison", "gym": "Gym / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Sports de plein air", "hiking": "Randonnée", "travel": "Voyage", "weekend-getaway": "Escapade de week-end", "holiday": "Vacances", "festival": "Festival", "sightseeing": "Tourisme"
        }
    },
    "he": {
        "colors": {
            "white": "לבן", "gray": "אפור", "fume": "פחם", "black": "שחור", "cream": "קרם", "beige": "בז'", "tan": "חום בהיר", "cinnamon": "קינמון", "earth": "אדמה", "chestnut": "ערמון", "plum": "שזיף", "khaki": "חאקי", "lemon": "לימון", "yellow": "צהוב", "gold": "זהב", "mustard": "חרדל", "peach": "אפרסק", "apricot": "משמש", "salmon": "סלמון", "orange": "כתום", "dusty-pink": "ורוד מאובק", "coral": "קורל", "pomegranate-red": "רימון", "red": "אדום", "cherry-red": "דובדבן", "dark-red": "בורדו", "pink": "ורוד", "fuchsia": "פוקסיה", "lilac": "לילך", "lavender": "לבנדר", "violet": "סגול", "purple": "ארגמן", "ice-blue": "תכלת", "turquoise": "טורקיז", "blue": "כחול", "saxony-blue": "כחול רויאל", "navy": "כחול נייבי", "mint": "מנטה", "water-green": "ירוק מים", "grass-green": "ירוק דשא", "emerald": "אזמרגד", "green": "ירוק", "olive": "זית", "silver": "כסף", "bronze": "ברונזה", "leopard": "מנומר", "zebra": "זברה", "snakeskin": "עור נחש", "striped": "פסים", "plaid": "משובץ", "floral": "פרחוני", "polka-dot": "נקודות"
        },
        "categories": {
            "top": "חולצות", "t-shirt": "טי-שירט", "blouse": "חולצה", "shirt": "חולצה מכופתרת", "sweater": "סוודר", "pullover": "סוודר", "sweatshirt": "סווטשירט", "hoodie": "קפוצ'ון", "track-top": "עליונית טרנינג", "crop-top": "קרופ טופ", "tank-top": "גופיה", "bodysuit": "בגד גוף", "vest": "וסט", "tunic": "טוניקה", "bralette": "ברלט", "bottom": "מכנסיים", "jeans": "ג'ינס", "trousers": "מכנסיים", "linen-trousers": "מכנסי פשתן", "leggings": "טייץ", "track-bottom": "מכנסי טרנינג", "mini-skirt": "חצאית מיני", "midi-skirt": "חצאית מידי", "long-skirt": "חצאית ארוכה", "denim-shorts": "מכנסי ג'ינס קצרים", "fabric-shorts": "מכנסי בד קצרים", "athletic-shorts": "מכנסי ספורט קצרים", "bermuda-shorts": "מכנסי ברמודה", "capri-pants": "מכנסי קאפרי", "dresses-jumpsuits": "שמלות ואוברולים", "casual-dress": "שמלת יום-יום", "evening-dress": "שמלת ערב", "sporty-dress": "שמלת ספורט", "modest-dress": "שמלה צנועה", "modest-evening-dress": "שמלת ערב צנועה", "jumpsuit": "אוברול", "romper": "אוברול קצר", "outerwear": "ביגוד עליון", "puffer-coat": "מעיל פוך", "raincoat": "מעיל גשם", "denim-jacket": "ג'קט ג'ינס", "leather-jacket": "ג'קט עור", "fabric-jacket": "ג'קט בד", "bomber-jacket": "ג'קט בומבר", "overcoat": "מעיל", "coat": "מעיל", "trenchcoat": "מעיל טרנץ'", "blazer": "בלייזר", "cardigan": "קרדיגן", "abaya": "עבאיה", "shoes": "נעליים", "sneakers": "סניקרס", "casual-sport-shoes": "נעלי ספורט קז'ואל", "heels": "עקבים", "boots": "מגפיים", "tall-boots": "מגפיים גבוהים", "flats": "נעליים שטוחות", "loafers": "לואפרים", "bootie": "מגפון", "sandals": "סנדלים", "slippers": "נעלי בית", "classic-shoes": "נעליים קלאסיות", "bags": "תיקים", "handbag": "תיק יד", "backpack": "תיק גב", "shoulder-bag": "תיק כתף", "briefcase": "תיק מסמכים", "crossbody-bag": "תיק צד", "accessories": "אביזרים", "necklace": "שרשרת", "earrings": "עגילים", "ring": "טבעת", "bracelet": "צמיד", "scarf": "צעיף", "hijab": "חיג'אב", "shawl": "שאל", "sunglasses": "משקפי שמש", "belt": "חגורה", "hat": "כובע", "watch": "שעון", "tie": "עניבה", "suits": "חליפות", "suit-jacket": "ג'קט חליפה", "suit-trousers": "מכנסי חליפה", "tuxedo": "טוקסידו", "polo-shirt": "חולצת פולו"
        },
        "occasions": {
            "categories": { "casual": "יומיומי", "work": "עבודה ומקצועי", "formal": "חגיגי ורשמי", "social": "חברתי", "active": "פעיל וספורט", "special": "נסיעות ומיוחד" },
            "daily-errands": "סידורים יומיים", "friends-gathering": "מפגש עם חברים", "weekend-brunch": "בראנץ' סוף שבוע", "coffee-date": "קפה", "shopping": "קניות", "walk": "הליכה", "office-day": "יום במשרד", "business-meeting": "פגישת עסקים", "business-lunch": "ארוחת צהריים עסקית", "networking": "אירוע נטוורקינג", "university": "אוניברסיטה / שיעור", "wedding": "חתונה", "special-event": "אירוע מיוחד", "celebration": "חגיגה", "formal-dinner": "ארוחת ערב רשמית", "dinner-date": "דייט לארוחת ערב", "birthday-party": "מסיבת יום הולדת", "concert": "הופעה", "night-out": "יציאה לילית", "house-party": "מסיבת בית", "gym": "חדר כושר / פיטנס", "yoga-pilates": "יוגה / פילאטיס", "outdoor-sports": "ספורט בחוץ", "hiking": "טיול רגלי", "travel": "נסיעה", "weekend-getaway": "חופשת סוף שבוע", "holiday": "חג", "festival": "פסטיבל", "sightseeing": "טיול"
        }
    },
    "es": {
        "colors": {
            "white": "Blanco", "gray": "Gris", "fume": "Carbón", "black": "Negro", "cream": "Crema", "beige": "Beige", "tan": "Canela", "cinnamon": "Canela", "earth": "Tierra", "chestnut": "Castaño", "plum": "Ciruela", "khaki": "Caqui", "lemon": "Limón", "yellow": "Amarillo", "gold": "Dorado", "mustard": "Mostaza", "peach": "Melocotón", "apricot": "Albaricoque", "salmon": "Salmón", "orange": "Naranja", "dusty-pink": "Rosa palo", "coral": "Coral", "pomegranate-red": "Granada", "red": "Rojo", "cherry-red": "Cereza", "dark-red": "Burdeos", "pink": "Rosa", "fuchsia": "Fucsia", "lilac": "Lila", "lavender": "Lavanda", "violet": "Violeta", "purple": "Morado", "ice-blue": "Azul hielo", "turquoise": "Turquesa", "blue": "Azul", "saxony-blue": "Azul real", "navy": "Azul marino", "mint": "Menta", "water-green": "Verde agua", "grass-green": "Verde hierba", "emerald": "Esmeralda", "green": "Verde", "olive": "Oliva", "silver": "Plata", "bronze": "Bronce", "leopard": "Leopardo", "zebra": "Cebra", "snakeskin": "Piel de serpiente", "striped": "Rayado", "plaid": "A cuadros", "floral": "Floral", "polka-dot": "De lunares"
        },
        "categories": {
            "top": "Parte de arriba", "t-shirt": "Camiseta", "blouse": "Blusa", "shirt": "Camisa", "sweater": "Suéter", "pullover": "Jersey", "sweatshirt": "Sudadera", "hoodie": "Sudadera con capucha", "track-top": "Chaqueta de chándal", "crop-top": "Top corto", "tank-top": "Camiseta de tirantes", "bodysuit": "Body", "vest": "Chaleco", "tunic": "Túnica", "bralette": "Bralette", "bottom": "Parte de abajo", "jeans": "Vaqueros", "trousers": "Pantalones", "linen-trousers": "Pantalones de lino", "leggings": "Leggings", "track-bottom": "Pantalón de chándal", "mini-skirt": "Minifalda", "midi-skirt": "Falda midi", "long-skirt": "Falda larga", "denim-shorts": "Shorts vaqueros", "fabric-shorts": "Shorts de tela", "athletic-shorts": "Shorts deportivos", "bermuda-shorts": "Bermudas", "capri-pants": "Pantalones capri", "dresses-jumpsuits": "Vestidos y monos", "casual-dress": "Vestido informal", "evening-dress": "Vestido de noche", "sporty-dress": "Vestido deportivo", "modest-dress": "Vestido recatado", "modest-evening-dress": "Vestido de noche recatado", "jumpsuit": "Mono", "romper": "Mono corto", "outerwear": "Ropa de abrigo", "puffer-coat": "Abrigo acolchado", "raincoat": "Chubasquero", "denim-jacket": "Chaqueta vaquera", "leather-jacket": "Chaqueta de cuero", "fabric-jacket": "Chaqueta de tela", "bomber-jacket": "Chaqueta bomber", "overcoat": "Abrigo", "coat": "Abrigo", "trenchcoat": "Gabardina", "blazer": "Blazer", "cardigan": "Cárdigan", "abaya": "Abaya", "shoes": "Zapatos", "sneakers": "Zapatillas", "casual-sport-shoes": "Zapatillas deportivas casual", "heels": "Tacones", "boots": "Botas", "tall-boots": "Botas altas", "flats": "Zapatos planos", "loafers": "Mocasines", "bootie": "Botín", "sandals": "Sandalias", "slippers": "Zapatillas de casa", "classic-shoes": "Zapatos clásicos", "bags": "Bolsos", "handbag": "Bolso de mano", "backpack": "Mochila", "shoulder-bag": "Bolso de hombro", "briefcase": "Maletín", "crossbody-bag": "Bandolera", "accessories": "Accesorios", "necklace": "Collar", "earrings": "Pendientes", "ring": "Anillo", "bracelet": "Pulsera", "scarf": "Bufanda", "hijab": "Hiyab", "shawl": "Chal", "sunglasses": "Gafas de sol", "belt": "Cinturón", "hat": "Sombrero", "watch": "Reloj", "tie": "Corbata", "suits": "Trajes", "suit-jacket": "Chaqueta de traje", "suit-trousers": "Pantalones de traje", "tuxedo": "Esmoquin", "polo-shirt": "Polo"
        },
        "occasions": {
            "categories": { "casual": "Casual", "work": "Trabajo y profesional", "formal": "Celebración y formal", "social": "Social", "active": "Activo y deportivo", "special": "Viajes y especial" },
            "daily-errands": "Recados diarios", "friends-gathering": "Reunión con amigos", "weekend-brunch": "Brunch de fin de semana", "coffee-date": "Cita para un café", "shopping": "De compras", "walk": "Un paseo", "office-day": "Día en la oficina", "business-meeting": "Reunión de negocios", "business-lunch": "Almuerzo de negocios", "networking": "Evento de networking", "university": "Universidad / Clase", "wedding": "Boda", "special-event": "Evento especial", "celebration": "Celebración", "formal-dinner": "Cena formal", "dinner-date": "Cita para cenar", "birthday-party": "Fiesta de cumpleaños", "concert": "Concierto", "night-out": "Salida nocturna", "house-party": "Fiesta en casa", "gym": "Gimnasio / Fitness", "yoga-pilates": "Yoga / Pilates", "outdoor-sports": "Deportes al aire libre", "hiking": "Senderismo", "travel": "Viaje", "weekend-getaway": "Escapada de fin de semana", "holiday": "Vacaciones", "festival": "Festival", "sightseeing": "Turismo"
        }
    },
    "ja": {
        "colors": {
            "white": "白", "gray": "グレー", "fume": "チャコール", "black": "黒", "cream": "クリーム", "beige": "ベージュ", "tan": "タン", "cinnamon": "シナモン", "earth": "アース", "chestnut": "チェスナット", "plum": "プラム", "khaki": "カーキ", "lemon": "レモン", "yellow": "黄色", "gold": "ゴールド", "mustard": "マスタード", "peach": "ピーチ", "apricot": "アプリコット", "salmon": "サーモン", "orange": "オレンジ", "dusty-pink": "ダスティローズ", "coral": "コーラル", "pomegranate-red": "ザクロ", "red": "赤", "cherry-red": "チェリー", "dark-red": "バーガンディ", "pink": "ピンク", "fuchsia": "フューシャ", "lilac": "ライラック", "lavender": "ラベンダー", "violet": "バイオレット", "purple": "紫", "ice-blue": "アイスブルー", "turquoise": "ターコイズ", "blue": "青", "saxony-blue": "ロイヤルブルー", "navy": "ネイビー", "mint": "ミント", "water-green": "アクアグリーン", "grass-green": "グラスグリーン", "emerald": "エメラルド", "green": "緑", "olive": "オリーブ", "silver": "シルバー", "bronze": "ブロンズ", "leopard": "レオパード", "zebra": "ゼブラ", "snakeskin": "スネークスキン", "striped": "ストライプ", "plaid": "チェック", "floral": "花柄", "polka-dot": "水玉"
        },
        "categories": {
            "top": "トップス", "t-shirt": "Tシャツ", "blouse": "ブラウス", "shirt": "シャツ", "sweater": "セーター", "pullover": "プルオーバー", "sweatshirt": "スウェットシャツ", "hoodie": "パーカー", "track-top": "トラックトップ", "crop-top": "クロップトップ", "tank-top": "タンクトップ", "bodysuit": "ボディスーツ", "vest": "ベスト", "tunic": "チュニック", "bralette": "ブラレット", "bottom": "ボトムス", "jeans": "ジーンズ", "trousers": "ズボン", "linen-trousers": "リネンパンツ", "leggings": "レギンス", "track-bottom": "トラックパンツ", "mini-skirt": "ミニスカート", "midi-skirt": "ミディスカート", "long-skirt": "ロングスカート", "denim-shorts": "デニムショーツ", "fabric-shorts": "布製ショーツ", "athletic-shorts": "アスレチックショーツ", "bermuda-shorts": "バミューダショーツ", "capri-pants": "カプリパンツ", "dresses-jumpsuits": "ドレス＆ジャンプスーツ", "casual-dress": "カジュアルドレス", "evening-dress": "イブニングドレス", "sporty-dress": "スポーティードレス", "modest-dress": "控えめなドレス", "modest-evening-dress": "控えめなイブニングドレス", "jumpsuit": "ジャンプスーツ", "romper": "ロンパース", "outerwear": "アウターウェア", "puffer-coat": "ダウンコート", "raincoat": "レインコート", "denim-jacket": "デニムジャケット", "leather-jacket": "レザージャケット", "fabric-jacket": "ファブリックジャケット", "bomber-jacket": "ボンバージャケット", "overcoat": "オーバーコート", "coat": "コート", "trenchcoat": "トレンチコート", "blazer": "ブレザー", "cardigan": "カーディガン", "abaya": "アバヤ", "shoes": "靴", "sneakers": "スニーカー", "casual-sport-shoes": "カジュアルスポーツシューズ", "heels": "ヒール", "boots": "ブーツ", "tall-boots": "ロングブーツ", "flats": "フラットシューズ", "loafers": "ローファー", "bootie": "ブーティ", "sandals": "サンダル", "slippers": "スリッパ", "classic-shoes": "クラシックシューズ", "bags": "バッグ", "handbag": "ハンドバッグ", "backpack": "バックパック", "shoulder-bag": "ショルダーバッグ", "briefcase": "ブリーフケース", "crossbody-bag": "クロスボディバッグ", "accessories": "アクセサリー", "necklace": "ネックレス", "earrings": "イヤリング", "ring": "リング", "bracelet": "ブレスレット", "scarf": "スカーフ", "hijab": "ヒジャブ", "shawl": "ショール", "sunglasses": "サングラス", "belt": "ベルト", "hat": "帽子", "watch": "腕時計", "tie": "ネクタイ", "suits": "スーツ", "suit-jacket": "スーツジャケット", "suit-trousers": "スーツパンツ", "tuxedo": "タキシード", "polo-shirt": "ポロシャツ"
        },
        "occasions": {
            "categories": { "casual": "カジュアル", "work": "仕事＆プロフェッショナル", "formal": "お祝い＆フォーマル", "social": "社交", "active": "アクティブ＆スポーツ", "special": "旅行＆特別" },
            "daily-errands": "日常の用事", "friends-gathering": "友人との集まり", "weekend-brunch": "週末のブランチ", "coffee-date": "コーヒー", "shopping": "ショッピング", "walk": "散歩", "office-day": "オフィスでの一日", "business-meeting": "ビジネスミーティング", "business-lunch": "ビジネスランチ", "networking": "ネットワーキングイベント", "university": "大学/授業", "wedding": "結婚式", "special-event": "特別イベント", "celebration": "お祝い", "formal-dinner": "フォーマルなディナー", "dinner-date": "ディナーデート", "birthday-party": "誕生日パーティー", "concert": "コンサート", "night-out": "夜遊び", "house-party": "ホームパーティー", "gym": "ジム/フィットネス", "yoga-pilates": "ヨガ/ピラティス", "outdoor-sports": "アウトドアスポーツ", "hiking": "ハイキング", "travel": "旅行", "weekend-getaway": "週末の小旅行", "holiday": "休日", "festival": "フェスティバル", "sightseeing": "観光"
        }
    },
    "ko": {
        "colors": {
            "white": "흰색", "gray": "회색", "fume": "차콜", "black": "검정색", "cream": "크림색", "beige": "베이지색", "tan": "황갈색", "cinnamon": "계피색", "earth": "흙색", "chestnut": "밤색", "plum": "자두색", "khaki": "카키색", "lemon": "레몬색", "yellow": "노란색", "gold": "금색", "mustard": "머스타드", "peach": "복숭아색", "apricot": "살구색", "salmon": "연어색", "orange": "주황색", "dusty-pink": "더스티 로즈", "coral": "산호색", "pomegranate-red": "석류색", "red": "빨간색", "cherry-red": "체리색", "dark-red": "버건디", "pink": "분홍색", "fuchsia": "푸크시아", "lilac": "라일락", "lavender": "라벤더", "violet": "바이올렛", "purple": "보라색", "ice-blue": "아이스 블루", "turquoise": "터키석색", "blue": "파란색", "saxony-blue": "로열 블루", "navy": "네이비", "mint": "민트", "water-green": "아쿠아 그린", "grass-green": "잔디 녹색", "emerald": "에메랄드", "green": "녹색", "olive": "올리브", "silver": "은색", "bronze": "청동색", "leopard": "레오파드", "zebra": "지브라", "snakeskin": "뱀피 무늬", "striped": "스트라이프", "plaid": "체크 무늬", "floral": "플로럴", "polka-dot": "폴카 도트"
        },
        "categories": {
            "top": "상의", "t-shirt": "티셔츠", "blouse": "블라우스", "shirt": "셔츠", "sweater": "스웨터", "pullover": "풀오버", "sweatshirt": "스웨트셔츠", "hoodie": "후드티", "track-top": "트랙탑", "crop-top": "크롭탑", "tank-top": "탱크탑", "bodysuit": "바디수트", "vest": "조끼", "tunic": "튜닉", "bralette": "브라렛", "bottom": "하의", "jeans": "청바지", "trousers": "바지", "linen-trousers": "리넨 바지", "leggings": "레깅스", "track-bottom": "트레이닝 바지", "mini-skirt": "미니 스커트", "midi-skirt": "미디 스커트", "long-skirt": "롱 스커트", "denim-shorts": "데님 반바지", "fabric-shorts": "면 반바지", "athletic-shorts": "운동용 반바지", "bermuda-shorts": "버뮤다 팬츠", "capri-pants": "카프리 팬츠", "dresses-jumpsuits": "원피스 & 점프수트", "casual-dress": "캐주얼 원피스", "evening-dress": "이브닝 드레스", "sporty-dress": "스포티 드레스", "modest-dress": "단정한 원피스", "modest-evening-dress": "단정한 이브닝 드레스", "jumpsuit": "점프수트", "romper": "롬퍼", "outerwear": "아우터", "puffer-coat": "패딩 코트", "raincoat": "레인코트", "denim-jacket": "데님 재킷", "leather-jacket": "가죽 재킷", "fabric-jacket": "패브릭 재킷", "bomber-jacket": "보머 재킷", "overcoat": "오버코트", "coat": "코트", "trenchcoat": "트렌치코트", "blazer": "블레이저", "cardigan": "가디건", "abaya": "아바야", "shoes": "신발", "sneakers": "스니커즈", "casual-sport-shoes": "캐주얼 스포츠화", "heels": "힐", "boots": "부츠", "tall-boots": "롱부츠", "flats": "플랫 슈즈", "loafers": "로퍼", "bootie": "부티", "sandals": "샌들", "slippers": "슬리퍼", "classic-shoes": "클래식 슈즈", "bags": "가방", "handbag": "핸드백", "backpack": "백팩", "shoulder-bag": "숄더백", "briefcase": "서류 가방", "crossbody-bag": "크로스바디백", "accessories": "액세서리", "necklace": "목걸이", "earrings": "귀걸이", "ring": "반지", "bracelet": "팔찌", "scarf": "스카프", "hijab": "히잡", "shawl": "숄", "sunglasses": "선글라스", "belt": "벨트", "hat": "모자", "watch": "시계", "tie": "넥타이", "suits": "정장", "suit-jacket": "정장 재킷", "suit-trousers": "정장 바지", "tuxedo": "턱시도", "polo-shirt": "폴로 셔츠"
        },
        "occasions": {
            "categories": { "casual": "캐주얼", "work": "업무 및 전문", "formal": "축하 및 공식", "social": "사교", "active": "활동 및 스포츠", "special": "여행 및 특별" },
            "daily-errands": "일상적인 용무", "friends-gathering": "친구 모임", "weekend-brunch": "주말 브런치", "coffee-date": "커피", "shopping": "쇼핑", "walk": "산책", "office-day": "사무실에서의 하루", "business-meeting": "비즈니스 미팅", "business-lunch": "비즈니스 런치", "networking": "네트워킹 이벤트", "university": "대학교 / 수업", "wedding": "결혼식", "special-event": "특별한 이벤트", "celebration": "축하", "formal-dinner": "정식 만찬", "dinner-date": "저녁 데이트", "birthday-party": "생일 파티", "concert": "콘서트", "night-out": "밤 외출", "house-party": "집들이", "gym": "헬스장 / 피트니스", "yoga-pilates": "요가 / 필라테스", "outdoor-sports": "야외 스포츠", "hiking": "등산", "travel": "여행", "weekend-getaway": "주말 여행", "holiday": "휴일", "festival": "축제", "sightseeing": "관광"
        }
    },
    "ru": {
        "colors": {
            "white": "Белый", "gray": "Серый", "fume": "Угольный", "black": "Черный", "cream": "Кремовый", "beige": "Бежевый", "tan": "Рыжевато-коричневый", "cinnamon": "Корица", "earth": "Землистый", "chestnut": "Каштановый", "plum": "Сливовый", "khaki": "Хаки", "lemon": "Лимонный", "yellow": "Желтый", "gold": "Золотой", "mustard": "Горчичный", "peach": "Персиковый", "apricot": "Абрикосовый", "salmon": "Лососевый", "orange": "Оранжевый", "dusty-pink": "Пыльная роза", "coral": "Коралловый", "pomegranate-red": "Гранатовый", "red": "Красный", "cherry-red": "Вишневый", "dark-red": "Бордовый", "pink": "Розовый", "fuchsia": "Фуксия", "lilac": "Сиреневый", "lavender": "Лавандовый", "violet": "Фиолетовый", "purple": "Фиолетовый", "ice-blue": "Ледяной синий", "turquoise": "Бирюзовый", "blue": "Синий", "saxony-blue": "Королевский синий", "navy": "Темно-синий", "mint": "Мятный", "water-green": "Аквамарин", "grass-green": "Травяной зеленый", "emerald": "Изумрудный", "green": "Зеленый", "olive": "Оливковый", "silver": "Серебряный", "bronze": "Бронзовый", "leopard": "Леопардовый", "zebra": "Зебра", "snakeskin": "Змеиная кожа", "striped": "Полосатый", "plaid": "Клетчатый", "floral": "Цветочный", "polka-dot": "В горошек"
        },
        "categories": {
            "top": "Верхняя одежда", "t-shirt": "Футболка", "blouse": "Блузка", "shirt": "Рубашка", "sweater": "Свитер", "pullover": "Пуловер", "sweatshirt": "Свитшот", "hoodie": "Худи", "track-top": "Спортивная кофта", "crop-top": "Кроп-топ", "tank-top": "Майка", "bodysuit": "Боди", "vest": "Жилет", "tunic": "Туника", "bralette": "Бралетт", "bottom": "Нижняя одежда", "jeans": "Джинсы", "trousers": "Брюки", "linen-trousers": "Льняные брюки", "leggings": "Леггинсы", "track-bottom": "Спортивные штаны", "mini-skirt": "Мини-юбка", "midi-skirt": "Миди-юбка", "long-skirt": "Длинная юбка", "denim-shorts": "Джинсовые шорты", "fabric-shorts": "Тканевые шорты", "athletic-shorts": "Спортивные шорты", "bermuda-shorts": "Бермуды", "capri-pants": "Брюки капри", "dresses-jumpsuits": "Платья и комбинезоны", "casual-dress": "Повседневное платье", "evening-dress": "Вечернее платье", "sporty-dress": "Спортивное платье", "modest-dress": "Скромное платье", "modest-evening-dress": "Скромное вечернее платье", "jumpsuit": "Комбинезон", "romper": "Ромпер", "outerwear": "Верхняя одежда", "puffer-coat": "Пуховик", "raincoat": "Плащ", "denim-jacket": "Джинсовая куртка", "leather-jacket": "Кожаная куртка", "fabric-jacket": "Тканевая куртка", "bomber-jacket": "Бомбер", "overcoat": "Пальто", "coat": "Пальто", "trenchcoat": "Тренч", "blazer": "Блейзер", "cardigan": "Кардиган", "abaya": "Абайя", "shoes": "Обувь", "sneakers": "Кроссовки", "casual-sport-shoes": "Повседневная спортивная обувь", "heels": "Каблуки", "boots": "Ботинки", "tall-boots": "Сапоги", "flats": "Балетки", "loafers": "Лоферы", "bootie": "Ботильоны", "sandals": "Сандалии", "slippers": "Тапочки", "classic-shoes": "Классическая обувь", "bags": "Сумки", "handbag": "Сумка", "backpack": "Рюкзак", "shoulder-bag": "Сумка через плечо", "briefcase": "Портфель", "crossbody-bag": "Кросс-боди", "accessories": "Аксессуары", "necklace": "Ожерелье", "earrings": "Серьги", "ring": "Кольцо", "bracelet": "Браслет", "scarf": "Шарф", "hijab": "Хиджаб", "shawl": "Шаль", "sunglasses": "Солнцезащитные очки", "belt": "Пояс", "hat": "Шляпа", "watch": "Часы", "tie": "Галстук", "suits": "Костюмы", "suit-jacket": "Пиджак", "suit-trousers": "Брюки от костюма", "tuxedo": "Смокинг", "polo-shirt": "Рубашка-поло"
        },
        "occasions": {
            "categories": { "casual": "Повседневные", "work": "Работа и Профессиональные", "formal": "Торжественные и Официальные", "social": "Социальные", "active": "Активные и Спортивные", "special": "Путешествия и Особые" },
            "daily-errands": "Повседневные дела", "friends-gathering": "Встреча с друзьями", "weekend-brunch": "Бранч на выходных", "coffee-date": "Кофе", "shopping": "Шопинг", "walk": "Прогулка", "office-day": "День в офисе", "business-meeting": "Деловая встреча", "business-lunch": "Деловой обед", "networking": "Сетевое мероприятие", "university": "Университет / Занятия", "wedding": "Свадьба", "special-event": "Особое событие", "celebration": "Праздник", "formal-dinner": "Официальный ужин", "dinner-date": "Свидание за ужином", "birthday-party": "Вечеринка в честь дня рождения", "concert": "Концерт", "night-out": "Вечерний выход", "house-party": "Домашняя вечеринка", "gym": "Тренажерный зал / Фитнес", "yoga-pilates": "Йога / Пилатес", "outdoor-sports": "Спорт на открытом воздухе", "hiking": "Поход", "travel": "Путешествие", "weekend-getaway": "Поездка на выходные", "holiday": "Праздник", "festival": "Фестиваль", "sightseeing": "Осмотр достопримечательностей"
        }
    },
    "hi": {
        "colors": {
            "white": "सफ़ेद", "gray": "ग्रे", "fume": "चारकोल", "black": "काला", "cream": "क्रीम", "beige": "बेज", "tan": "टैन", "cinnamon": "दालचीनी", "earth": "मिट्टी", "chestnut": "चेस्टनट", "plum": "बेर", "khaki": "खाकी", "lemon": "नींबू", "yellow": "पीला", "gold": "सुनहरा", "mustard": "सरसों", "peach": "आड़ू", "apricot": "खुबानी", "salmon": "सैल्मन", "orange": "नारंगी", "dusty-pink": "धूल भरा गुलाब", "coral": "मूंगा", "pomegranate-red": "अनार", "red": "लाल", "cherry-red": "चेरी", "dark-red": "बरगंडी", "pink": "गुलाबी", "fuchsia": "फ्यूशिया", "lilac": "लिलैक", "lavender": "लैवेंडर", "violet": "बैंगनी", "purple": "बैंगनी", "ice-blue": "बर्फ नीला", "turquoise": "फ़िरोज़ा", "blue": "नीला", "saxony-blue": "शाही नीला", "navy": "नेवी", "mint": "पुदीना", "water-green": "एक्वा हरा", "grass-green": "घास हरा", "emerald": "पन्ना", "green": "हरा", "olive": "जैतून", "silver": "चांदी", "bronze": "कांस्य", "leopard": "तेंदुआ", "zebra": "ज़ेबरा", "snakeskin": "सांप की खाल", "striped": "धारीदार", "plaid": "प्लेड", "floral": "पुष्प", "polka-dot": "पोल्का डॉट"
        },
        "categories": {
            "top": "ऊपरी वस्त्र", "t-shirt": "टी-शर्ट", "blouse": "ब्लाउज", "shirt": "शर्ट", "sweater": "स्वेटर", "pullover": "पुलओवर", "sweatshirt": "स्वेटशर्ट", "hoodie": "हूडी", "track-top": "ट्रैक टॉप", "crop-top": "क्रॉप टॉप", "tank-top": "टैंक टॉप", "bodysuit": "बॉडीसूट", "vest": "वेस्ट", "tunic": "ट्यूनिक", "bralette": "ब्रैलेट", "bottom": "निचले वस्त्र", "jeans": "जीन्स", "trousers": "पतलून", "linen-trousers": "लिनन पतलून", "leggings": "लेगिंग्स", "track-bottom": "ट्रैक बॉटम", "mini-skirt": "मिनी स्कर्ट", "midi-skirt": "मिडी स्कर्ट", "long-skirt": "लंबी स्कर्ट", "denim-shorts": "डेनिम शॉर्ट्स", "fabric-shorts": "फैब्रिक शॉर्ट्स", "athletic-shorts": "एथलेटिक शॉर्ट्स", "bermuda-shorts": "बरमूडा शॉर्ट्स", "capri-pants": "कैप्री पैंट", "dresses-jumpsuits": "ड्रेस और जंपसूट", "casual-dress": "कैज़ुअल ड्रेस", "evening-dress": "शाम की ड्रेस", "sporty-dress": "स्पोर्टी ड्रेस", "modest-dress": "मामूली ड्रेस", "modest-evening-dress": "मामूली शाम की ड्रेस", "jumpsuit": "जंपसूट", "romper": "रॉम्पर", "outerwear": "बाहरी वस्त्र", "puffer-coat": "पफर कोट", "raincoat": "रेनकोट", "denim-jacket": "डेनिम जैकेट", "leather-jacket": "चमड़े की जैकेट", "fabric-jacket": "फैब्रिक जैकेट", "bomber-jacket": "बॉम्बर जैकेट", "overcoat": "ओवरकोट", "coat": "कोट", "trenchcoat": "ट्रेंचकोट", "blazer": "ब्लेज़र", "cardigan": "कार्डिगन", "abaya": "अबाया", "shoes": "जूते", "sneakers": "स्नीकर्स", "casual-sport-shoes": "कैज़ुअल स्पोर्ट शूज़", "heels": "हील्स", "boots": "बूट्स", "tall-boots": "लंबे बूट्स", "flats": "फ्लैट्स", "loafers": "लोफर्स", "bootie": "बूटी", "sandals": "सैंडल", "slippers": "चप्पलें", "classic-shoes": "क्लासिक जूते", "bags": "बैग", "handbag": "हैंडबैग", "backpack": "बैकपैक", "shoulder-bag": "शोल्डर बैग", "briefcase": "ब्रीफकेस", "crossbody-bag": "क्रॉसबॉडी बैग", "accessories": "सहायक उपकरण", "necklace": "हार", "earrings": "झुमके", "ring": "अंगूठी", "bracelet": "कंगन", "scarf": "स्कार्फ", "hijab": "हिजाब", "shawl": "शॉल", "sunglasses": "धूप का चश्मा", "belt": "बेल्ट", "hat": "टोपी", "watch": "घड़ी", "tie": "टाई", "suits": "सूट", "suit-jacket": "सूट जैकेट", "suit-trousers": "सूट पतलून", "tuxedo": "टक्सीडो", "polo-shirt": "पोलो शर्ट"
        },
        "occasions": {
            "categories": { "casual": "कैज़ुअल", "work": "कार्य और व्यावसायिक", "formal": "उत्सव और औपचारिक", "social": "सामाजिक", "active": "सक्रिय और खेल", "special": "यात्रा और विशेष" },
            "daily-errands": "दैनिक कार्य", "friends-gathering": "दोस्तों के साथ मिलना", "weekend-brunch": "सप्ताहांत का ब्रंच", "coffee-date": "कॉफी डेट", "shopping": "खरीदारी", "walk": "एक सैर", "office-day": "कार्यालय में एक दिन", "business-meeting": "व्यावसायिक बैठक", "business-lunch": "व्यावसायिक दोपहर का भोजन", "networking": "नेटवर्किंग कार्यक्रम", "university": "विश्वविद्यालय / कक्षा", "wedding": "शादी", "special-event": "विशेष कार्यक्रम", "celebration": "उत्सव", "formal-dinner": "औपचारिक रात्रिभोज", "dinner-date": "डिनर डेट", "birthday-party": "जन्मदिन की पार्टी", "concert": "संगीत कार्यक्रम", "night-out": "रात में बाहर घूमना", "house-party": "घर की पार्टी", "gym": "जिम / फिटनेस", "yoga-pilates": "योग / पिलेट्स", "outdoor-sports": "आउटडोर खेल", "hiking": "लंबी पैदल यात्रा", "travel": "यात्रा", "weekend-getaway": "सप्ताहांत की छुट्टी", "holiday": "छुट्टी", "festival": "त्योहार", "sightseeing": "दर्शनीय स्थलों की यात्रा"
        }
    }
}


def get_translation(lang_code: str, key: str, default_lang: str = 'en'):
    """
    Belirtilen dil ve anahtar için çeviri sözlüğünü alır.
    Bulamazsa, varsayılan dildeki çeviriyi döner.
    """
    return TRANSLATIONS.get(lang_code, TRANSLATIONS[default_lang]).get(key, {})